### ISSUE TITLE
possible missing geometry

### ISSUE THREAD

**Issue by anandthakker** [mapbox/tippecanoe#115]
Related to https://github.com/developmentseed/vt-geojson/issues/8, there may be some kind of input case that's causing tippecanoe to produce some tiles containing features who are missing a `geometry`.  I asked @aaronpdennis for a subset of the input that reproduces the issue, but figured I'd go ahead and report it in case there's a known/obvious reason that this is happening.

**Comment by ericfischer** [comment]
Thanks for the report. I don't know of any existing problems with this but would love to have to have the test case. If the missing geometry is a polygon, there have been a lot of polygon changes recently and some versions were definitely not producing them correctly.

**Comment by ericfischer** [comment]
Looking at the tile mentioned in https://github.com/developmentseed/vt-geojson/issues/8#issuecomment-157282153 it's all point features, the last of which apparently doesn't have any geometry. I'm not sure if tippecanoe will actually produce that if you give it a GeoJSON with a feature with empty geometry, but I'll check.

**Comment by ericfischer** [comment]
Tippecanoe does specifically exclude features that have empty geometries, normally so that it doesn't spend space on features that have been simplified or clipped away. I don't think tippecanoe would have produced this tile.

**Comment by anandthakker** [comment]
Huh. That's what I figured, too... @aaronlidman can you confirm your source was built with tippecanoe?   @ericfischer if so, maybe something weird happened at some post processing step?

**Comment by ericfischer** [comment]
It's possible, but unless there is compositing, I don't think anything on the server side ever unpacks the vector data to transform it, and only passes it through unchanged. Do you have the original `mbtiles` to make sure the tile in it matches what is being served?

**Comment by anandthakker** [comment]
@ericfischer alas, nope... we'll have to wait for @aaronpdennis on that.

**Comment by aaronpdennis** [comment]
@anandthakker @ericfischer The source was built with tippecanoe. I'm going to try and reproduce the error and report back here.

**Comment by aaronpdennis** [comment]
Unfortunately I don't have the original `mbtiles` file that resulted in the developmentseed/vt-geojson#8 error.

I've since recreated the tiles and the processing I was trying to do works just fine, but I'm still noticing strange behavior.

When I view the data in Mapbox Studio I'm noticing one tile from my tippecanoe generated source fails to render. The points I expect in `16/19087/24820` never appear, but they render fine at zoom 17.

*This command on the full geojson:*
`tippecanoe -o possible-missing-geometry.mbtiles -f -l points -n 'Possible Missing Geometry' -z 19 -Z 16 -b 0 -g 0 -r 0 original.geojson`

*One tile fails to render after upload to Mapbox:*
![tile-fails-to-render](https://cloud.githubusercontent.com/assets/8019997/11348609/73cad636-91f5-11e5-9c4c-fe07bbc416e5.gif)

I clipped that geojson file `[ -75.157470703125, 39.95185892663004, -75.146484375, 39.9602803542957 ]` in QGIS and ran the same tippecanoe process on the output geojson and this time the same points render just fine.

*This command on the clipped geojson:*
`tippecanoe -o possible-missing-geometry-clipped.mbtiles -f -l points -n 'Possible Missing Geometry Clipped' -z 19 -Z 16 -b 0 -g 0 -r 0 clipped.geojson`

*All tiles render fine after upload to Mapbox:*
![clipped-able-to-render](https://cloud.githubusercontent.com/assets/8019997/11348930/5ce5bb14-91f7-11e5-9083-a7314d93e265.gif)

[Here is the clipped version of the geojson.] (https://gist.github.com/aaronpdennis/25997c02936a80aa99e8) The full geojson dataset is ~250mb.

**Comment by ericfischer** [comment]
Does the tile that doesn't draw appear in `possible-missing-geometry.mbtiles`? Wondering whether it is tippecanoe failing to include it or whether it is somehow not unpacking properly after uploading.

**Comment by aaronpdennis** [comment]
I'm able to style the tile source just fine Mapbox Studio Classic, which tells me the data for that tile is in the `mbtiles` file.

Can you recommend a tool for checking on that tile within the file?

**Comment by ericfischer** [comment]
Sorry to miss this earlier @aaronpdennis. If you have a recent copy of tippecanoe, the `tippecanoe-decode` tool will translate vector mbtiles back to GeoJSON, or if you just want to make sure the tile is present at all, `tippecanoe-enumerate` will list the tiles within an mbtiles.

**Comment by aaronpdennis** [comment]
Just used `tippecanoe-decode` to confirm that tile which had problems rendering did contain all the right points. Made a visual comparison with the `tippecanoe-decode` output geojson and original geojson in QGIS. Seems to be no issue with Tippecanoe.

**Comment by ericfischer** [comment]
There's not a remaining tippecanoe problem here, right?
