### ISSUE TITLE
Tiles for more zoom levels 

### ISSUE THREAD

**Issue by divya1c** [mapbox/tippecanoe#171]
Hi! 

I am using this command line to convert my json to mbtiles file. 
tippecanoe -o tipp_out.mbtiles -z10 ogr_out.json

But , I still get a message saying :
*** NOTE TILES ONLY COMPLETE THROUGH ZOOM 3 ***

Am I using the command line wrong? Thanks!

**Comment by ericfischer** [comment]
This means that tippecanoe was not able to make one of your zoom level 4 tiles small enough to fit within the 500K limit per tile. Without knowing more about your data, it is hard to say what you could have done differently to make it succeed.

If you have lots of attributes on your features, try using `-x` to remove attributes that aren't needed for display. If your geometries are points, try using `-B` to set a higher base zoom level so that the low zooms aren't as dense.

You can also use `-pd` to make it arbitrarily throw away enough features at random to make it succeed, although this will probably cause undesirable visible artifacts.
