### ISSUE TITLE
Create MBtiles with several layers from single file

### ISSUE THREAD

**Issue by DaZzz** [mapbox/tippecanoe#188]
I would really appreciate this feature. Basically what I want is writing something like this

```
{
  "type": "FeatureCollection",
  "features": [
   {
     "type": "Feature",
     "properties": {
        "name": "layer-name", // this 
        "layer": "layer-name" // or maybe this
      },
      "geometry": {
        "type": "MultiLineString",
        "coordinates": []
      },
      "tippecanoe": {
        "minzoom": 1,
        "maxzoom": 12
      }
    },
    // other features ...
  ]
}
```

to generate different layers. One layer for each feature from feature collection.

**Comment by ericfischer** [comment]
That would be nice. Tippecanoe-decode already outputs

```
{ "type": "FeatureCollection", "properties": { "layer": "layername" }, "features": [ ... ] }
```

because I had to output the name somehow and that seemed to make sense. Maybe it should be in a "tippecanoe" extension field instead.

The hardest part, I think, is that if the FeatureCollection is written in a different order, since you can put the fields of a JSON object in any order, Tippecanoe might not see the layer name declaration until after the features are already encoded, so I need to figure out how to handle that. I guess the worst case is that it could detect that it happened and issue an error message.

**Comment by DaZzz** [comment]
@ericfischer :+1: `tippecanoe` extension field would be better indeed.

**Comment by ericfischer** [comment]
Looking at this more: the other thing that makes it really messy is that splitting the input stage across multiple threads really doesn't work at all if there is a wrapper FeatureCollection that they all need to pay attention to, since the threads that start reading at some arbitrary line part of the way into the file have no idea what outer object encloses the text they are reading. So to support both parallelism and layer tagging, the layer name would have to be tagged on individual features, not on the FeatureCollection.

(There also needs be some shared state between threads to ensure that each of them uses the same layer numbers for the same layer names, but that's a less fundamental problem.)

**Comment by DaZzz** [comment]
@ericfischer actually tagging layer name for individual feature is exactly what I need. You can see that from my example. I'm not sure that it will suit for everyone though.

**Comment by ericfischer** [comment]
Oh, sorry, I misread it! OK, I will try to get it working with tags on individual features when I have a chance.

**Comment by ericfischer** [comment]
Specifying layer names in the GeoJSON is in https://github.com/mapbox/tippecanoe/pull/294.
