### ISSUE TITLE
Question: creating different layers from many json input files

### ISSUE THREAD

**Issue by liebrand** [mapbox/tippecanoe#197]
Hi there,

Quick question: I have half a dozen or so directories, each filled with thousands of geojson files. I would like to convert these to an mbtiles file, where each directory becomes a layer.

I know I can cat all geojson files from one directory and pipe it to tippecanoe to create one layer, but how can I create x layers from x directories, each of which has multiple (thousands) of files?

Ideally actually, I would do this on a bunch of machines in parallel. Each machine creating one layer. And then do some sort of mbtile merge for every layer in to one single mbtiles file.

But I haven't found a way to merge mbtiles? Is there such a thing? (I thought tile-join could help, but that appears to be just to merge in some attributes from a csv file?)

**Comment by ericfischer** [comment]
@liebrand There is not a good way to do this currently. Tile-join has some limited ability to join tilesets together, but not where the same zoom/x/y tile is defined in multiple tilesets, even if they are different layers. There was [a recent request](https://github.com/mapbox/tippecanoe/issues/188) to let individual features be tagged with a desired layer name, so that might be a solution if I can get it working, but it doesn't work yet.

The most promising direction is that most current Unix shells have a redirection syntax where you could do

    tippecanoe -o whatever.mbtiles <(cat layer1/*.json) <(cat layer2/*.json)

to treat the two directories of files as separate input streams and therefore separate layers, but the layers would be given nonsensical names so that isn't very helpful. Maybe I could add a special syntax so you could say

    tippecanoe -o whatever.mbtiles -Llayer1:<(cat layer1/*.json) -Llayer2:<(cat layer2/*.json)

and specify the layer name and the input stream separately as part of an option. That shouldn't be too hard to add.

**Comment by liebrand** [comment]
That'd be great if you could add that! Let me know if you need me to test it or anything...

As a side note, another improvement might be to be able to specify the -z and -Z params "per layer"... but that's not crucial for me right now....

**Comment by ericfischer** [comment]
@liebrand I'll try to get the named-layer option working. You can at least specify the zoom range for individual features with the

    "tippecanoe": { "minzoom": …, "maxzoom": … }

syntax, but am having a hard time thinking of a good per-layer or per-file syntax for options in general.

**Comment by ericfischer** [comment]
Working on this in https://github.com/mapbox/tippecanoe/pull/199

**Comment by ericfischer** [comment]
OK, seems to work now.

**Comment by liebrand** [comment]
Awesome, thanks! Will try this out tonight! (I assume I just build from tip of master; or did you also make a brew update?)

**Comment by ericfischer** [comment]
I tagged a release but didn't update homebrew, so you'll need to build from source to try this right away.

**Comment by timiyay** [comment]
@liebrand @ericfischer I opened a PR to update the homebrew formula about 20 minutes ago, so it should go through in the next few hours

**Comment by ericfischer** [comment]
Thank you @timiyay! I hope it helps with your problem too.

**Comment by ericfischer** [comment]
Specifying layer names in the GeoJSON is in https://github.com/mapbox/tippecanoe/pull/294.
