### ISSUE TITLE
Features at Z 0 bounds dropped

### ISSUE THREAD

**Issue by dnomadb** [mapbox/tippecanoe#20]
It seems as if features that intersect the bounds of a Z0 tile (`-180.0, -85.0511287798066, 180.0, 85.0511287798066` - both at that zoom and at all higher zooms) are being dropped.

![image](https://cloud.githubusercontent.com/assets/5084513/5963806/3e48575e-a7a4-11e4-991b-275abae31679.png)
_Note the white border - [slippy](https://api.tiles.mapbox.com/v4/dnomadb.e69980c6/page.html?access_token=pk.eyJ1IjoiZG5vbWFkYiIsImEiOiJEak5aTXdZIn0.UtQIRl-MzHHZk6TIAHSWww#1/17/-17)_

I am not sure if just the vertices at these bounds are being dropped, or the whole feature is not being included.

cc @ericfischer

**Comment by ericfischer** [comment]
Thanks @dnomadb. This is actually a different problem than I thought it was, because the code that I thought was in error actually only clips off anything with a latitude above the Web Mercator ceiling of 85.0511 degrees and doesn't do anything with longitude. I'll figure out what's going wrong and fix it.

**Comment by ericfischer** [comment]
It looks like this is a bug in the old, bottom-up indexing, and has been fixed since 0b84f1315928720.

**Comment by dnomadb** [comment]
Awesome, thanks @ericfischer. Has the fix been published to `brew`?

**Comment by ericfischer** [comment]
@dnomadb Yes, looks like it got merged. https://github.com/Homebrew/homebrew/pull/36367
