### ISSUE TITLE
'Polygon clean failed' Error Msg

### ISSUE THREAD

**Issue by jaylev1** [mapbox/tippecanoe#205]
Hi -

I'm frequently getting the 'Polygon clean failed' error msg when using Tippecanoe and have a few questions about it:

1. What happens when a polygon clean fails? Does Tippecanoe have a way to recover from the failure or is this polygon excluded from my tileset?

1. What would cause this failure? Is there any easy way to fix my underlying data so that it wouldn't happen?

1. Could we possibly have a command line argument to suppress this warning? I'm getting a lot of them, and useful information that I'd like to see (e.g tile 5/7/12 size is 698955 with detail 9, >500000) quickly rolls off the screen.

Thanks,
Jay

**Comment by ericfischer** [comment]
@jaylev1 I'm working on cleaning this up now, so hopefully it should get better soon.

Polygon cleaning is when Tippecanoe calls the [Clipper](http://www.angusj.com/delphi/clipper.php) library to try to clean up contradictions in polygons (places where one polygon ring cuts across another ring or one of its own edges, or where multiple rings share an edge), so that the geometry that makes it into the tile is "strictly simple" and can be rendered efficiently on the client side.

The error message comes up when Clipper returns an error trying to clean the polygon. I believe in this case it returns an empty geometry so the feature does not make it into the tile.

I have only seen this happen myself in data that is in the wrong projection, so there is a polygon with hundreds of sides that are directly on top of each other or a pixel apart in the tile. There are probably other ways to cause it, but I'm hazy on the details because Clipper isn't my own code.

Other than blatantly wrong geometries like that, I don't know a way to clean up the source data to avoid the problem, since a lot of the contradictions happen because of Tippecanoe scaling and quantizing the coordinates to the tile resolution, not because of problems in the original data.

I'll add a check now so that it will only issue the warning once.

**Comment by ericfischer** [comment]
What version of Tippecanoe are you using, by the way? Anything since 1.9.3 (c66fd315e) should do better with some polygons that used to give errors.

**Comment by jaylev1** [comment]
I'm using 1.9.2, so I'll be sure to upgrade.

Thanks for the clarification and for tweaking the warning.

**Comment by ericfischer** [comment]
Warning quieted in https://github.com/mapbox/tippecanoe/pull/206. Will merge once tests pass.

**Comment by ericfischer** [comment]
Merged.
