### ISSUE TITLE
Generating QA tiles using minur and tippecanoe

### ISSUE THREAD

**Issue by jasonbeverage** [mapbox/tippecanoe#266]
I'm trying to generate some QA tiles on my own, so I want to generate full resolution, unsimplified data at a given lod.

I think I've got the command line down but I wanted to see if there something I was missing 

Basically I want to use osmfilter to filter out some pieces of osm that I want and then generate full resolution, unsimplified tiles at a fixed zoom level.

So something like:
osmfilter planet-latest.osm.pbf --keep= *somecriteria* -o=filtered.o5m
osmconvert filtered.o5m -o=filtered.pbf
minjur -p filtered.pbf | tippecanoe --no-polygon-splitting --no-line-simplification --no-feature-limit --no-tile-size-limit --no-duplication -Z 13 -z 13 --buffer=0 -o filtered.mbtiles

Is that similar to what MapBox is using to generate your QA tiles or is there another flag I'm missing?

Thanks!

**Comment by ericfischer** [comment]
Osm-qa-tiles is doing something quite similar, but uses `-d20` to generate very high-resolution tiles (1048576x1048576 units instead of 4096x4096), and does not use `--no-polygon-splitting` or `--no-duplication`.

Please be careful with your polygon options: it may be extremely slow to do the polygon cleaning on polygons that are unsplit, unsimplified, and not divided between tiles.

**Comment by ericfischer** [comment]
Closing this unless there are further questions
