### ISSUE TITLE
Process large collections of GeoJSON features problem 

### ISSUE THREAD

**Issue by beyoung** [mapbox/tippecanoe#267]
I'm dealing with a huge collections of geojson of trajectory, which are stored into a single geojson file , and the size is 5.3G. my server memory is 8G. when i run  `tippecanoe -o china-route-heatmap.mbtiles a.geojson` , system killed tippecanoe .   and i use dmesg tool to find the reason, it says that:

[8920020.512834] [22373]  1000 22336  1974378  1824261    3816        0             0 tippecanoe
[8920020.512835] Out of memory: Kill process 22373 (tippecanoe) score 894 or sacrifice child
[8920020.512893] Killed process 22373 (tippecanoe) total-vm:7897512kB, anon-rss:7297040kB, file-rss:4kB

how do i deal with this situation?  split huge single geojson into some small files ?  or other methods?

Thanks!

**Comment by morganherlocker** [comment]
That server's memory is cutting it pretty close, but you might have some luck splitting your geojson file from a giant featurecollection format like [this](https://gist.githubusercontent.com/morganherlocker/5fcd8493e0e53bfe59ae1ca45a57f01c/raw/9e17987d30e5d9804be4fad1afb34cdc56bda275/fc.json) to a line-delimitted format like [this](https://gist.githubusercontent.com/morganherlocker/5fcd8493e0e53bfe59ae1ca45a57f01c/raw/9e17987d30e5d9804be4fad1afb34cdc56bda275/ld.json)

You can then pipe your data to tippecanoe line by line like this:

```sh
cat data.json | tippecanoe -o china-route-heatmap.mbtiles
```

**Comment by morganherlocker** [comment]
Also, there are many options for splitting up your data, but I would check out [jq](https://stedolan.github.io/jq/) if you want to stream this in bash or a library like JavaScript's [JSONStream](https://github.com/dominictarr/JSONStream) for other languages. These will let you incrementally parse your giant JSON object and give it to tippecanoe one small piece at a time, rather than loading everything into memory at once.

**Comment by ericfischer** [comment]
It's unusual for tippecanoe to run out of memory like this unless all the data is very concentrated geographically. Splitting the input up into multiple files won't help, because the input will be parsed serially no matter how many files it comes from.

Were there any warning messages or other output during parsing or tiling before it ran out of memory? Do you have a fairly recent version of tippecanoe?

The best advice I can offer is to try something like `tippecanoe -g2` to thin out densely overlapping features, which otherwise all have to be in memory at the same time.

**Comment by beyoung** [comment]
@morganherlocker  many thanks . I'm trying to deal with my dataset with your method.

**Comment by beyoung** [comment]
@ericfischer  i run it in background model , there weren't any other warning or  error messages .
And my tippecanoe version is 1.9.11.

**Comment by ericfischer** [comment]
@beyoung It might help to upgrade, because 1.11.6 and 1.11.7 introduce some features to reduce memory usage.

Nothing looks unreasonable about your sample input, but if you can exclude the `cmt` or `name` properties, it should help, because unique strings consume a lot more space than geometry alone does.

**Comment by beyoung** [comment]
@morganherlocker    @ericfischer  Thanks for your help , i update my tippecanoe to v1.12.2 and change my dataset format to [this](https://gist.githubusercontent.com/morganherlocker/5fcd8493e0e53bfe59ae1ca45a57f01c/raw/9e17987d30e5d9804be4fad1afb34cdc56bda275/ld.json),and exclude the cmt or name properties, but when my dataset size increase to 6G ,the same issue happens. I want to know must i incresse my memory to deal with it? if so, and how to evaluate memory accoding datasets size . ( in the future , the dataset may increase to 30G or 100G  ).  
Thanks!

**Comment by ericfischer** [comment]
@beyoung I don't know. If you can provide a copy of your dataset, or even the log of tippecanoe's progress output while it is running, I can look into it, but I don't know at what stage of processing the memory is running out.

You probably have more features than can fit into one tile, but tippecanoe doesn't know that there are too many features until it has loaded at least all the features from that one tile into memory, and the problems will only get worse as your data gets larger.

You could try

    tippecanoe --drop-lines -rg -Bg

to figure out early on what fraction of features need to be dropped from each tile to limit it to at most 50,000 features per tile, which should limit the per-tile memory need.

**Comment by ericfischer** [comment]
Closing this since there's nothing I can do without a sample of the data that isn't working.
