### ISSUE TITLE
Specify layer name in GeoJSON extension

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/tippecanoe#286]
@ericfischer - Could we add the ability to specify a layer name in the GeoJSON extension?

Right now we're abusing the ability to have different files go to different layers ("If multiple files are specified, each is placed in its own layer.") but it's getting to be too many files and having them all in a single file would be helpful.

I imagine it being something like this:
```
{
    "type" : "Feature",
    "tippecanoe" : { "maxzoom" : 9, "minzoom" : 4, "layer": "xyz" },
    "properties" : { "FULLNAME" : "N Vasco Rd" },
    "geometry" : <geometry>
}

```

Is this technically possible? How many layers are possible for a single tile?

cc @nickcordella

**Comment by ericfischer** [comment]
Sure, I should be able to add an extension like this with a little bit of restructuring. As far as I know the vector tile spec doesn't limit the number of layers. I don't know if there is a number that starts to make rendering slow down, or whether you will run into the feature limit before that becomes a problem.

**Comment by aaronlidman** [comment]
Awesome, thanks. Not super urgent, just something that would be helpful for debugging a few things.

**Comment by ericfischer** [comment]
(Thinking out loud: Either the GeoJSON parsing could serialize these layer tags as a string, to be resolved during tiling, or immediately resolve the layer name to a layer number.

It is probably better to do the resolution immediately instead of deferring it until tiling, since the mbtiles metadata has to be able to produce a list of all the layers that appear in any tile, but doing that the straightforward way would require a global name to number mapping table that can be both read and written from multiple parser threads, and the locking around that table could be slow.

To have both fast parsing and global access, it will be best to have a layer table per parser thread. But this means that both tiling and mbtiles-writing will have to have logic to merge different-numbered layers from different threads that have the same name into one effective layer.)

**Comment by ericfischer** [comment]
The other thing that is a mess is that the mbtiles metadata has a list of keys per layer, so fabricating new layers also requires fabricating new sets of keys. The keys for each layer are currently merged at the end of parallel parsing of the layer.

**Comment by nickcordella** [comment]
It sounds like there are complications with this implementation.So as far as I know the only reason we want to specify the layer name is because mbview shows each layer in a random color, which is convenient for my specific use case but probably not the

**Comment by ericfischer** [comment]
It has been requested before (https://github.com/mapbox/tippecanoe/issues/197, https://github.com/mapbox/tippecanoe/issues/188), so you are not the only person who has wanted it.

**Comment by ericfischer** [comment]
This is getting close to ready in https://github.com/mapbox/tippecanoe/pull/294

**Comment by nickcordella** [comment]
perfect timing. I am getting close to wanting to use it. (not yet though - no rush).
