### ISSUE TITLE
Generating detailed tiles at high zoom levels with 1GB dense geojson

### ISSUE THREAD

**Issue by iskandarblue** [mapbox/tippecanoe#320]
I have a dense polygon layer of land parcels 1 GB in size  (similar to issue #311) with about 450k records.  I've managed to generate tiles up to zoom level 12, but they are very very far from ideal.    

You can download the json file [here](https://drive.google.com/open?id=0BxKUeZA_oaslbXVyTHlZNk1zdWM).

<img width="1002" alt="screen shot 2016-11-19 at 11 48 25 am" src="https://cloud.githubusercontent.com/assets/8308461/20457113/58a3e684-ae52-11e6-82a7-209167b13fd2.png">

In QGIS, the layer looks like this: 
<img width="770" alt="screen shot 2016-11-19 at 11 56 01 am" src="https://cloud.githubusercontent.com/assets/8308461/20457120/72366234-ae52-11e6-8afb-e95777978306.png">

The set of options that I tried that produced the best output so far was
`$ tippecanoe -o -f parcel06.mbtiles --drop-polygons  -rg  -Bg  parcel06cert.json`

Any suggestions on how to create tiles at zoom levels 13 -22 and preserve topology? 

I have also tried uploading the json to PostgreSQL and serving up tiles using [tilesplash](https://github.com/faradayio/tilesplash), but rendering tiles this way is very inefficient.

I'm running on MacOSX using latest version `tippecanoe v1.14.4`

Any suggestions would be greatly appreciated!

**Comment by ericfischer** [comment]
Thanks for the sample parcel file.

The thing that is really hurting you at the high zoom levels is that your polygons all have a large number of attributes, so there is very little space left in the tile for geometry after the attributes are accounted for. The only way it is going to work reasonably is to keep the vector tiles restricted to just the data that is needed to draw the shapes, plus a unique key that you can use to look up the other data from some other file when you need it.

For instance, you could do

    tippecanoe -f -o parcel06.mbtiles -y ACCT_ --drop-densest-as-needed parcel06cert.json

(using the new dropping option from https://github.com/mapbox/tippecanoe/pull/312) to keep *only* the geometry and the `ACCT_` id (so you can use the `ACCT_` to look up the other data when you need it).

That leaves the area of your QGIS screenshot (approximately #11.86/32.7969/-96.7499) looking like this:

![screen shot 2016-11-21 at 10 52 02 am](https://cloud.githubusercontent.com/assets/1951835/20496121/ba0b9a98-afd8-11e6-9593-07ea0124deee.png)

(not perfect, but reasonably usable), and keeps complete feature coverage at z13 and beyond. You may find `--drop-fraction-as-needed` or `--drop-smallest-as-needed` to produce more appealing results at the medium zooms, since each of them has a different tradeoff.

**Comment by iskandarblue** [comment]
Thank you very much for this helpful answer! 

I've just tried running that code but am encountering an error that `--drop-densest-as-needed` is not an option: 

```
Alexanders-MacBook-Pro:parcel06cert alexander$ tippecanoe -f -o parcel06.mbtiles -y ACCT_ --drop-densest-as-needed parcel06cert.json
tippecanoe: unrecognized option --drop-densest-as-needed
Usage: tippecanoe --output=output.mbtiles [--name=...] [--layer=...]
         [--attribution=...] [--named-layer=...] [--maximum-zoom=...]
         [--minimum-zoom=...] [--base-zoom=...] [--full-detail=...]
         [--low-detail=...] [--minimum-detail=...] [--exclude=...]
         [--include=...] [--drop-rate=...] [--buffer=...]
         [--temporary-directory=...] [--gamma=...] [--prevent=...]
         [--additional=...] [--projection=...] [--simplification=...]
         [--exclude-all] [--force] [--allow-existing] [--quiet]
         [--version] [--read-parallel] [--coalesce] [--reverse]
         [--reorder] [--drop-lines] [--check-polygons]
         [--drop-polygons] [--prefer-radix-sort]
         [--calculate-feature-density] [--detect-shared-borders]
         [--no-line-simplification] [--simplify-only-low-zooms]
         [--no-feature-limit] [--no-tile-size-limit]
         [--force-feature-limit] [--preserve-input-order]
         [--no-polygon-splitting] [--no-clipping]
         [--no-duplication] [file.json ...]
```
Have I not updated `tippecanoe` properly? 
I've downloaded the latest release from October 18, unzipped the folder and hit `make`

**Comment by ericfischer** [comment]
It's still only in a pull request (https://github.com/mapbox/tippecanoe/pull/312, the `dynamic-gamma` branch), so `git checkout dynamic-gamma` and `make` again should get it for you.

I'll do a little more cleanup and merge it soon, because it's not doing anybody any good sitting in a branch forever.

**Comment by ericfischer** [comment]
These changes are merged to the `master` branch now, if you want to `git pull` and `make` again.

**Comment by iskandarblue** [comment]
I'm still receiving the same error.  I've did `git checkout dynamic-gamma` and then hit `make` but how do I install this new version globally?

**Comment by ericfischer** [comment]
You can use `make install` to install it globally.

**Comment by ericfischer** [comment]
Closing unless there are further actions here.
