### ISSUE TITLE
Combine features, aggregate properties to fit tiles option

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/tippecanoe#324]
## Motivation

Create visually and analytically useful spatial bins from aggregated feature data.  

## Proposal

Add a processing option to tippecanoe to merge and aggregate nearby features to keep tiles under size and feature limits.

## Details

I generate a dense hexbinned geojson data. Each polygon in the geojson file has `count` and `speed` properties.  There are 1 million polygon features in the tile at z10.  

I want to pass the geojson file to tippecanoe with a new processing option `--merge-and-aggregate`.  

This option would:

1. Combine nearby features into one feature 
    * Effectively this would make a coarser hex or square grid (100mx100x --> 500mx500m, etc)
2. SUM numeric properties together and add them to the new combined feature

## Utility

1. Visualization
    * Accurately represent an area at any zoom level using data properties, like speed, density, or engine RPM's.
2. Analytics
    * Query source data at any zoom level on a client application (GL JS or GL Native) and reliably use that data for spatial analysis - point in polygon, intersect, union, etc
    * EX: Determine the highest density foot traffic area within 3 blocks of my retail store.
    * EX: Correlate traffic speed and density to traffic collisions based on location.

cc @ericfischer @bkowshik

**Comment by ericfischer** [comment]
@ryanbaumann The aggregating of polygons is kind of what I've already been trying to do in https://github.com/mapbox/tippecanoe/issues/311 with `--merge-polygons-as-needed`. I'm still not sure whether gridding makes the problem easier or harder, but I should try it and find out.

To truly combine features, instead of sampling them, I think this will need a full syntax for describing what to do with attributes rather than just summing them. In your example with `count` and `speed`, you would probably want to take the sum of the `count` but the geometric mean of the `speed`, and both would need to be weighted within each grid square according to the fraction of the original feature that ended up within the square.

**Comment by ericfischer** [comment]
https://github.com/berlinermorgenpost/cogran has some interesting ideas about how to scale data associated with polygons to other polygons with different shapes but covering the same area.

https://github.com/mapbox/tippecanoe/pull/325 adds an option to snap low-zoom polygons to a grid, if you want to try it out. You also need to specify a resolution for the grid with `-D`:

    tippecanoe -o out.mbtiles -D8 --grid-low-zooms --no-polygon-splitting in.geojson

It does *not* merge any attributes of the features, but only snaps all the coordinates to the tile grid, so features are either stretched out to meet the grid or left out if they are entirely in the cracks in between the grid lines.

**Comment by ryanbaumann** [comment]
@ericfischer https://github.com/berlinermorgenpost/cogran is awesome - thanks for sharing.  Exploring now.

I think that visually #325 will help a lot - testing it now!  For any sort of analytics, the aggregated property value needs integrity.  Pre-binning the data before passing to Tippecane and specifying the zoom level in the feature JSON works great.

**Comment by ericfischer** [comment]
The other angle on this that might be worth exploring is adding a binning feature to Tippecanoe, so that you could provide your data as points, rather, than polygons, and Tippecanoe could bin them as it creates each zoom, with an option like `--bin=square` or `--bin=hex` to say what kind of bin, and `--bins=8` to say how many of them should exist along each tile dimension. Tippecanoe could add a `"bin-count": 27` attribute to the bin polygons to say how many points were binned into them.

That still leaves open the question of whether it could only bin points that have identical attributes, or whether it could also bin points that are not the same, and, if so, how to specify which attributes should be summed or averaged or concatenated or whatever else.

**Comment by ryanbaumann** [comment]
@ericfischer that would be great!  Raw event data is usually point data to begin with.  Having an tippecanoe option to bin point data into `hex` or `square` bins based on zoom level would be extremely useful.  

Property aggregation would bet the next step.  I'm not sure how useful the geometric binning would be without some sort of property aggregation - at the very least, a `count` property denoting the number of points contained within the bin would be needed.

**Comment by ericfischer** [comment]
Rather than make binning a feature directly in Tippecanoe, I am working on a general plugin interface (https://github.com/mapbox/tippecanoe/issues/329) so that Tippecanoe can call out to Turf to do zoom-level specific binning (or any other operation) during tiling.

**Comment by ryanbaumann** [comment]
@ericfischer this is brilliant - will add notes to the extension ticket and try to contribute!

**Comment by ryanbaumann** [comment]
I think we can close this now that the binning and filtering plugins are complete!
