### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by devTristan** [mapbox/tippecanoe#33]
I'm trying to use this on a 4.0G line-delimited geojson file. One point per line, 80 million or so points. Looks like this:

```console
cat lights.json | tippecanoe -o lights.mbtiles -l lights -n "Night time lights" -z8 -Z3
```

The file looks like this:
```json
{"type":"Point","coordinates":[-110,34]}
{"type":"Point","coordinates":[-110.1,34.1]}
etc
```

It eats up 120G of RAM very quickly (2-3 minutes) then is killed by the kernel. Any way around this?

**Comment by springmeyer** [comment]
Please profile the process with Activity Monitor (if you are on OSX) or `perf top` if you are on linux (https://github.com/springmeyer/profiling-guide) and share the callstack you see before it gets killed.

**Comment by ericfischer** [comment]
The core problem is that the records in your file aren't GeoJSON features. They should look like:

    { "type": "Feature", "properties": { }, "geometry": { "type": "Point", "coordinates": [-110,34] } }

instead, so it is building a parse tree in memory for the entire thing while it looks for "type": "Feature" somewhere in your file, and never finding it so the tree just gets bigger and bigger.

I'll add a check to make it complain if it has read a long way into the file without ever finding any features, so that it won't just bloat endlessly.

**Comment by ericfischer** [comment]
@devTristan, I added an error message in 167ec69 to stop the parser before it consumes tons of memory.

**Comment by devTristan** [comment]
Thanks! I'm running it with a newline-delimited set of GeoJSON features now.
