### ISSUE TITLE
Inconsistent point dropping

### ISSUE THREAD

**Issue by gonesurfing** [mapbox/tippecanoe#330]
This may already be solved, but I'm not sure of the best way to address it:

I have a large rectangular grid of wind points in geojson format with feature properties of "start" (timestamp ####), "magnitude", "direction".  I would like to have layer points dropped as a user zooms out. This does work , but erratically. I think it is because tippecanoe sees points stacked on top of one another and because it doesn't know it's a time series it randomly picks some to drop at different zoom levels.

I'm trying to get around this by creating multiple grid densities and feeding the geojson a "tippecanoe":{"maxzoom": #, "minzoom": #}, but this is rather cumbersome and I'm having trouble getting it to work.

Is there a simple way to tell tippecanoe that all points at properties: {"start" == #### }should be treated as a set? When I upload a geojson directly into map box, it appears to do this automagically, but tippecanoe, not so much.

Thanks

**Comment by gonesurfing** [comment]
I've got this working now with the JSON "tippecanoe":{"maxzoom": #, "minzoom": #} switch. A breadcrumb for anyone in the future up against this, use '-r 0' on the command line to specify no point dropping or the zoom settings seem to be overridden.

Still seems like there should be a way to group based on a feature property like a timestamp. It would greatly simplify things in the future.

**Comment by gonesurfing** [comment]
One other note: 
"tippecanoe":{"maxzoom": 8, "minzoom": 0} means the feature starts at zero and is shown until zoom reaches 9. It looks like rather than a cutoff point, "8" matches anything from "8.0" to "8.999...". Not sure if this is intentional or not.

**Comment by ericfischer** [comment]
Thanks. Glad you got it working with the minzoom/maxzoom attributes. That's a good point that anything that has explicitly specified zoom levels probably shouldn't be subject to general dot-dropping.

I think the only reason you are seeing the behavior you want from direct GeoJSON upload to mapbox.com is that (like `-r0`) it never drops any features even at low zooms, so if the low-zoom tiles are too big, they just aren't generated at all instead of having their feature set reduced.

You're right that maxzoom of 8 means that features are still visible at 8.5. Tippecanoe only creates tiles with integer zoom levels; the interpolation in between is up to the renderer, which overzooms lower-zoom tiles instead of underzooming higher-zoom tiles.

I could probably get a feature working to treat features with identical locations the same for feature-dropping if that would still be useful to you. I'm not quite sure how clustering by properties would work, but I'll think about it, and will welcome any suggestions you might have for a good syntax for talking about feature ordering.

**Comment by gonesurfing** [comment]
I think clustering by identical location would be useful. However now that I think about it more for my particular case, the JSON min/max makes more sense.

Is there any reason to not enforce -r0 if one or both of max/min zoom are set in the JSON? I would think this would be the expected behavior and prevent frustration for others in the future.

**Comment by ericfischer** [comment]
Yes, that makes sense and I'll get a PR going to make that change.

**Comment by ericfischer** [comment]
Will be fixed in https://github.com/mapbox/tippecanoe/pull/331
