### ISSUE TITLE
-Z flag set but lower zoomlevels get still processed

### ISSUE THREAD

**Issue by indus** [mapbox/tippecanoe#340]
I want to process each z-level separately so I set ```-z``` = ```-Z``` and this gives the correct results. But what I observe from the shell-output is, that z-levels < ```-Z``` are also processed, while they luckily don´t get written to the mbtiles file.
Looks to me like this makes the processing time a lot longer then necessary.
Is there a way to completly avoid  0 to ```-Z``` levels.

Nevertheless I wanted to thank you for your work. i'm so glad that I found tippecanoe.

**Comment by ericfischer** [comment]
@indus Some of the processing still has to take place at low zooms to subdivide the features into the higher-zoom tiles that they will eventually end up in. It will skip over as many intermediate zooms as it can given the number of CPUs your computer has and the number of files it can have open at one time, but it will always need to look at zoom level 0 and possibly some others in between.

There might be some possibility of optimizing for non-global data sets by finding the single highest-zoom tile that all the features fit in. For instance if all your features are in Germany it could start with 4/8/5 instead of working all the way from 0/0/0.

**Comment by ericfischer** [comment]
Should be fixed in https://github.com/mapbox/tippecanoe/pull/341

**Comment by indus** [comment]
Thanks for the quick response ;-)

**Comment by ericfischer** [comment]
Thanks for suggesting the improvement!
