### ISSUE TITLE
How to install tippecanoe in Ubuntu?

### ISSUE THREAD

**Issue by Rub21** [mapbox/tippecanoe#36]
@ericfischer , Is there a way to  install tippecanoe in Ubuntu? 

cc/. @ianshward @ajashton @yhahn

**Comment by ericfischer** [comment]
You should be able to build and install it on Ubuntu by doing "make" and "make install" in the directory, but there's not currently a prebuilt package if that's what you're looking for, @Rub21.

**Comment by Rub21** [comment]
Working now.
Thanks.

**Comment by tkayne23** [comment]
Eric,
I'm trying to install using ubuntu 14.04. I ran the following commands:
git clone https://github.com/mapbox/tippecanoe.git
cd tippecanoe
make
make install

I get the following error:
g++ -I/usr/local/include -I. -g -Wall -Wshadow -03 -DNDEBUG -std=c++11 -c -o tile.o tile.cpp
tile.cpp:14:18: fatal error: zlib.h: no such file or directory
#include <zlib.h>

can you help me?

**Comment by timiyay** [comment]
@tkayne23

From the look of that output, your Ubuntu is missing `zlib`. This is caused by 1 of 2 issues:

1. the `zlib` library isn't installed
2. the `zlib` library _is_ installed, but its development headers aren't

Issue 2 is a common gotcha when installing packages on Linux. The development headers are needed for other libraries, like `tippecanoe` to use `zlib` for their own purposes. These libraries usually have the same name, with a `-dev` suffix.

In this case, if you google for `install zlib on ubuntu`, you'll see the library you need is called `zlib1g`. You can then run `sudo apt-cache search zlib1g`, which then show some package options.

The final command you'll need is:

```
sudo apt-get install zlib1g zlib1g-dev
```

**Comment by tkayne23** [comment]
Thank you. The installs seems to have worked after I

**Comment by tkayne23** [comment]
It did work after I installed zliblg zliblg-dev.

**Comment by ericfischer** [comment]
Thanks. I'll add that to the README in case other people have systems where zlib isn't installed.

**Comment by geraldo** [comment]
Another note for install on Ubuntu: You also have to add libsqlite3-dev

**Comment by ericfischer** [comment]
Thanks. This is in the README:

    sudo apt-get install build-essential libsqlite3-dev zlib1g-dev
