### ISSUE TITLE
Can I control the resolution of each level?

### ISSUE THREAD

**Issue by lihuadong1988** [mapbox/tippecanoe#362]
like the info below?
Tile Info:
Height: 256
Width: 256
DPI: 96
Levels of Detail: 5
Level ID: 0 [ Start Tile, End Tile ]
Resolution: 1.903568804664224E-5
Scale: 8000
Level ID: 1 [ Start Tile, End Tile ]
Resolution: 9.51784402332112E-6
Scale: 4000
Level ID: 2 [ Start Tile, End Tile ]
Resolution: 4.75892201166056E-6
Scale: 2000
Level ID: 3 [ Start Tile, End Tile ]
Resolution: 2.37946100583028E-6
Scale: 1000
Level ID: 4 [ Start Tile, End Tile ]
Resolution: 1.18973050291514E-6
Scale: 500

**Comment by lihuadong1988** [comment]
what does "tile detail" do ?

**Comment by ericfischer** [comment]
The detail is the log2 of the resolution of the tile, so `-d8` would be 256 units per tile, `-d9` would be 512, `-d10` would be 1024, and so on. Currently the only option is to specify the `detail` at maxzoom vs at all other zooms rather than specifying each zoom individually.

What are you trying to do? I don't think I really understand.

**Comment by lihuadong1988** [comment]
@ericfischer i want to specify the map resolution of each zoom level,for zoom level 0,the resolution is Resolution: 1.903568804664224E-5,and so on,how can i do that?

**Comment by ericfischer** [comment]
What are the units on that resolution of 1.903568804664224E-5? Meters?

The z0 tile covers the entire world, so for the normal detail of 12, one tile unit is 360 / 2^12 / .00000274 feet = 32077 feet = 9780 meters.

**Comment by lihuadong1988** [comment]
what's the difference between "tile detail" and "tile size"?

**Comment by lihuadong1988** [comment]
@ericfischer what's the difference between "tile detail" and "tile size"?they are the same?

**Comment by ericfischer** [comment]
When I say "tile detail" I am talking about the resolution of the integer coordinate system within each tile, so a "detail of 12" means that locations within the tile are snapped to a 4096x4096 grid (2^12 = 4096).

When I say "tile size" I am talking about the number of bytes that it takes to store the compressed data for each tile. Usually this is in the context of the 500,000 byte limit that the Mapbox service imposes on tile sizes.

**Comment by ericfischer** [comment]
I see now that the

    Level ID: 0 [ Start Tile, End Tile ]

thing is something that shows up in ArcGIS MapServer metadata files. What they call "levels of detail" is what I call "maxzoom" so that is probably the start of the confusion.

I finally understand the unit: the "resolution" is the size of a pixel in EPGS:3857 pseudo-meters. For 256x256 tiles, MapServer files have

```
Height: 256
Width: 256
DPI: 96
Levels of Detail: 20
    Level ID: 0 [ Start Tile, End Tile ]
        Resolution: 156543.033928
        Scale: 5.91657527591555E8
```

which comes from

    6378137 * π * 2 / 256 = 156543

(the EPGS:3857 radius of the world, converted to circumference by multiplying by 2π, and then dividing by the tile resolution), and

    (6378137 * π * 2) / (256 / 96 * 2.54 / 100) = 591658700

(the EPGS:3857 radius of the world, converted to circumference by multiplying by 2π, and then dividing by the size of a tile on screen in meters: 256 pixels at 96 dpi, converted to cm by multiplying by 2.54, converted to meters by dividing by 100).

So in the case of tiles from Tippecanoe, the values for the z0 tile with default detail `-d12`, and ordinarily taking up 512 pixels on screen, are:

    Resolution: 6378137 * π * 2 / (2^12) = 9783.939
    Scale: (6378137 * π * 2) / (512 / 96 * 2.54 / 100) = 295829350.4

Each additional zoom beyond z0 doubles the resolution and halves the scale.
