### ISSUE TITLE
Possible to generate raw .pbf files?

### ISSUE THREAD

**Issue by JamesMilnerUK** [mapbox/tippecanoe#383]
Firstly thanks for such a fantastic tool and all the work you folks put in!

My query is around the ability to get .pbf files from tippecanoe. Currently it appears tippecanoe exports to .mbtiles format as the only export option.

At the moment for our use case we have to run tippecanoe > mbutil > un-gzip > raw protobuf which is unfortunately extra work as i would assume the pbfs are compressed and then put into the SQLite database in the tippecanoe operation. Is there any realistic way to go from tippecanoe > raw protobuf? 

If it's not something currently implemented or that's not on your foreseeable roadmap, would you be open to a potential pull request?

**Comment by ericfischer** [comment]
This isn't something I had thought about because most users of tippecanoe want mbtiles (and mbutil is generally good enough to get the data out if you do want one particular tile), but there is no reason it couldn't write the data to a file instead of doing the sqlite insert.

I'd welcome a pull request that makes it do what you need. [This line in tile.cpp](https://github.com/mapbox/tippecanoe/blob/8c6f6250b1c36e0293f71f7f892ca857b6249741/tile.cpp#L1912) is where the data gets written to the mbtiles file. You would also need to make a change to [the call to tile.encode()](https://github.com/mapbox/tippecanoe/blob/8c6f6250b1c36e0293f71f7f892ca857b6249741/tile.cpp#L1840), which assumes that the caller will want the PBF to be compressed.

If you are OK with using mbutil as part of the process, it might be easier to add just a `--no-pbf-compression` option instead of an entirely separate output pipeline for plain files.

**Comment by JamesMilnerUK** [comment]
Hey @ericfischer, great stuff thanks for the points in the right direction. One of the interns I am working with is looking to create a pull request for this feature (I'm not particularly well versed in C++ unfortunately!) so hopefully expecting something from us by then :)

**Comment by ericfischer** [comment]
Merged in https://github.com/mapbox/tippecanoe/pull/389

**Comment by thunderkid** [comment]
For anyone using this answer directly (as I did) instead of reading the docs, the flag now seems to be called `--no-tile-compression`. And it was what I needed in order to get pbf files serving from s3. So thanks for the flag!
