### ISSUE TITLE
reduce to point

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/tippecanoe#438]
For low zooms and tiny polygons a rendered triangle 1px width would become indistinguishable from a 0.5px radius circle. Would tippecanoe determine when polygons and linestrings are so tiny that it makes sense to convert them to a point geometry.

**Comment by ericfischer** [comment]
I use a small polygon instead of a point to represent tiny polygons because the styling of points and polygons is completely different. If the polygons were reduced to points, the polygon style for the larger polygons wouldn't work on them.

**Comment by andrewharvey** [comment]
True, styling is different, but if you're running something like GL JS's querySourceFeatures having a point is enough locate the feature and get an id property. The motivation here is that a point is going to use less space from the 500K tile limit quota than a polygon, right?

**Comment by ericfischer** [comment]
Unfortunately, I don't think it actually helps very much because the four sides of the "tiny polygon" square are always exactly the same (three relative moves and a closepath) so they compress really well.

I just tried this on the San Francisco parcel map, with attributes removed, to z9, so there is almost nothing in the tileset except tiny polygons, and it only reduced the size to 98.8% of its previous size.

**Comment by andrewharvey** [comment]
> I don't think it actually helps very much because the four sides of the "tiny polygon" square are always exactly the same (three relative moves and a closepath) so they compress really well.

Good point! Thanks for validating this, I'll close this as reducing to points won't make much of a difference.
