### ISSUE TITLE
Tileset miss points from Dataset

### ISSUE THREAD

**Issue by bravecow** [mapbox/tippecanoe#441]
Tileset:

![image](https://user-images.githubusercontent.com/988471/28430698-22b62652-6d8a-11e7-95e3-544a2a31a032.png)

Dataset:

![image](https://user-images.githubusercontent.com/988471/28430731-3d15176a-6d8a-11e7-8ddc-4248aa505fba.png)

file:

https://www.dropbox.com/s/llereylclykdwje/buildings.geojson?dl=0

I even removed all properties from features, but polygons are corrupted anyway. Please, help 🙏

**Comment by ericfischer** [comment]
Works for me:

```
$ tippecanoe -f -o buildings.mbtiles buildings.geojson
For layer 0, using name "buildingsgeojson"
1602 features, 98317 bytes of geometry, 4 bytes of separate metadata, 0 bytes of string pool
  99.9%  14/9577/5520
```

![screen shot 2017-07-20 at 10 51 40 am](https://user-images.githubusercontent.com/1951835/28431526-7ee044a4-6d39-11e7-94d1-1eaa69088d18.png)


If you are manually setting a maxzoom, you may be setting it too low.

**Comment by bravecow** [comment]
Hm. I am creating tileset from dataset through Export to tileset button in studio. Should I do it manually? Studio has some limitations for free users? Thanks!

**Comment by ericfischer** [comment]
I don't know very much about how dataset exports in Studio work, unfortunately. It is probably making a bad guess about what the maxzoom should be, and I don't think there is an interface for correcting it. I would suggest using Tippecanoe to create an mbtiles tileset and uploading it manually so that you have more control over the process.

**Comment by bravecow** [comment]
Heh, spent a lot of time today to solve this issue through Studio. Thank you! Closing.
