### ISSUE TITLE
Getting 'detail' and 'resolution' right...

### ISSUE THREAD

**Issue by jliebrand** [mapbox/tippecanoe#452]
Hey there - this isn't really a bug, but more a request for help. I've been trying to get my head around the 'detail' parameter, and understanding how best to tweak the various parameters on tippecanoe to get "smoothing of features" at lower zoom levels to work well, but I think I'm either not understanding it, or just not quite getting my numbers right.

I took the land polygons from open street:
http://data.openstreetmapdata.com/land-polygons-split-3857.zip

Then converted the shp to geojson:
ogr2ogr -f "GeoJSON" land-polygons.json land-polygons-split-3857/land_polygons.shp -t_srs EPSG:4326

And then ran tippecanoe over that:
tippecanoe -P -z12 -Bg -rg -pt -as -pg -o test.mbtiles -Llndpol:land-polygons.json

Outcome:
https://api.mapbox.com/styles/v1/liebrand/cj6ezunxd220y2smxwxd9x85j.html?title=true&access_token=pk.eyJ1IjoibGllYnJhbmQiLCJhIjoiY2lld2FpcXpkMTJpbjkxbTNzZGU1YXl6OCJ9.akW57lx-2jkyO6IohS6yfA#3.39/50.27/-3.35

As you can see, there are lots a tiles that appear missing, which I'm guessing is because of the -as ?
But also, as you zoom out, the detail is far too great, rather than getting smooth coastlines, it's showing too much detail.

I'm guessing the default detail of 12 is too high? or at least for the lower zoom levels?

**Comment by ericfischer** [comment]
The detail at low zooms used to be 8, but this aggravated some bugs in software that wrongly assumed that tiles always had a resolution of 4096x4096 instead of checking the extent, so I changed the default to be 12 in every case to work around that.

I'll download your file and take a look.

**Comment by jliebrand** [comment]
Awesome, thanks!

**Comment by ericfischer** [comment]
I think your main problem is that `-pt` is counterproductive: instead of merging tiny polygons into placeholders, you are keeping them all as individual features, which then means there are too many features, so `-as` has to drop some of them, and sometimes it chooses badly. The output of

    tippecanoe -P -zg -pg -o test.mbtiles -Llndpol:land-polygons.json

looks basically correct to me.

There is a limitation to how much simplification Tippecanoe can possibly do to the low-zoom coastlines because your features on the coasts are all small, and it can only reduce the number of points within each feature, not combine them together for simplification.

Lowering the low zoom detail with `-D` just looks bad, because then you can see the results of the tiny-polygon merging as individual squares instead of having them be lost into something smaller than a pixel.

**Comment by jliebrand** [comment]
I used to not have -pt and indeed things looked better, but at zoom 0, 1 and 2 things did get blocky. So I assumed that was caused by merging tiny polygons in to squares. I'll take -pt out and see if that looks better.

But good to get confirmed that -D should not really be needed to be changed.

**Comment by ericfischer** [comment]
Great! Please reopen if there are further problems.

**Comment by jliebrand** [comment]
I'm not sure I can reopen an issue, but it still doesn't look quite right. The end result is a *much* smaller mbtileset, which is nice. But as you zoom out, the world becomes extremely blocky:

https://api.mapbox.com/styles/v1/liebrand/cj6ezunxd220y2smxwxd9x85j.html?fresh=true&title=true&access_token=pk.eyJ1IjoibGllYnJhbmQiLCJhIjoiY2lld2FpcXpkMTJpbjkxbTNzZGU1YXl6OCJ9.akW57lx-2jkyO6IohS6yfA#0.92/0/26

Also, if you zoom in a little, it seems that the land to the east of the meridian line is treated different from the west (or maybe this is tile caching issue):
https://api.mapbox.com/styles/v1/liebrand/cj6ezunxd220y2smxwxd9x85j.html?fresh=true&title=true&access_token=pk.eyJ1IjoibGllYnJhbmQiLCJhIjoiY2lld2FpcXpkMTJpbjkxbTNzZGU1YXl6OCJ9.akW57lx-2jkyO6IohS6yfA#2.14/23.72/11.66

Also attaching a screenshot
<img width="818" alt="screen shot 2017-08-18 at 11 33 00" src="https://user-images.githubusercontent.com/23407884/29455439-06b6f1bc-8409-11e7-9afb-d233517395da.png">

**Comment by jliebrand** [comment]
Here is another example, using a different land layer in my dataset:
https://api.mapbox.com/styles/v1/liebrand/cj6hqndrd4m2s2qrs9aha2ipo.html?fresh=true&title=true&access_token=pk.eyJ1IjoibGllYnJhbmQiLCJhIjoiY2lld2FpcXpkMTJpbjkxbTNzZGU1YXl6OCJ9.akW57lx-2jkyO6IohS6yfA#4.38/50.654/-0.032

And screenshots of the UK zoomed out and in:
<img width="122" alt="screen shot 2017-08-18 at 11 35 36" src="https://user-images.githubusercontent.com/23407884/29455561-7f1db4c4-8409-11e7-9831-5d9a3156bbb3.png">

<img width="433" alt="screen shot 2017-08-18 at 11 35 46" src="https://user-images.githubusercontent.com/23407884/29455564-84066b98-8409-11e7-82a8-5a21e8acba35.png">

**Comment by ericfischer** [comment]
Are you using the exact same data and command line you sent me? And are you getting any warning messages about lowering detail or anything? Because what I get from

    tippecanoe -P -zg -pg -o test.mbtiles -Llndpol:land-polygons.json

looks like this:

![screen shot 2017-08-18 at 10 13 07 am](https://user-images.githubusercontent.com/1951835/29469609-e4619d52-83fd-11e7-9978-732f9556c9f8.png)

https://api.mapbox.com/styles/v1/enf/cj6i4tw3m501c2spgm32j6a2r.html?title=true&access_token=pk.eyJ1IjoiZW5mIiwiYSI6IkNJek92bnMifQ.xn2_Uj9RkYTGRuCGg4DXZQ#2.52/31.35/-40.26

You must be doing something different (more attributes?) that is causing your detail to drop to 8 or maybe even 7, making the tiny polygon placeholders visible.

If you do have more attributes that are making each feature take up more space, your only options are to have fewer features or to show them at lower resolution. If you have some features that have the same attributes, use `--coalesce` to combine each of them into a single feature at least.

I think `--drop-smallest-as-needed` is going to be the best thing for this data, since the coastal polygons that it is going to drop are the ones you are going to want to drop anyway to keep the interiors contiguous. It looks pretty reasonable to me, using an artificially lowered maximum tile size of 200,000:

    tippecanoe -f -P -z11 --drop-smallest-as-needed -M200000 -o test.mbtiles -Llndpol:land-polygons.json

It drops 98% of the features at z0, but it still basically looks OK because they are tiny slivers of the coasts.

![screen shot 2017-08-18 at 10 56 57 am](https://user-images.githubusercontent.com/1951835/29471218-078db634-8404-11e7-9140-92700c02775a.png)

**Comment by jliebrand** [comment]
Aaahhh.... I have other layers, and they might indeed have a ton of attributes I don't need; causing the tile size to increase for no good reason.

Let me work on that and see if that helps. And if not, I'll use the drop smallest as needed.

I'll let you know how I get on

**Comment by jliebrand** [comment]
Sweet! Removing spurious unwanted attributes did the trick! Thanks for all your help!

**Comment by ericfischer** [comment]
Great, glad it's working for you now!
