### ISSUE TITLE
Filtering by attribute value

### ISSUE THREAD

**Issue by dylanparry** [mapbox/tippecanoe#453]
Hi,

Is it possible for me to generate an mbtiles file from a JSON file where the resulting file only contains those features where an attribute matches a particular value? For example, I have some roads data and I'd like to generate mbtiles files where `classification == "motorway"` and another for `classification == "a road" && primary == true`. Is anything like this possible with Tippecanoe, or am I best pre-processing this data in a GIS?

Thanks,

Dylan

**Comment by ericfischer** [comment]
I started [a ticket](https://github.com/mapbox/tippecanoe/issues/106) for this a long time ago and then never did it because I wasn't sure what syntax it should use.

At this point I think I would suggest using Mike Bostock's [ndjson-filter](https://github.com/mbostock/ndjson-cli#filter) to do the filtering.

**Comment by dylanparry** [comment]
Thanks. That looks like it should be able to do what I'm after. I'm struggling to figure out how to write the correct commands though.

What I think I need to do is pipe the contents of my JSON file (it's pretty big though, ~3.2GB) to `ndjson-filter` and then pipe the output from that to `tippecanoe`. Is that correct? Would you be able to help me with an example that would do that?

Thanks :)

**Comment by ericfischer** [comment]
If your data is already close to being formatted as newline-delimited JSON (as in, each Feature is on its own line, and stands alone except for maybe having a comma on the end), you can do something like:

    cat tl_2015_06001_roads.json | grep '"Feature"' | sed 's/,$//' | ndjson-filter 'd.properties.MTFCC === "S1400"' | tippecanoe -f -o s1400.mbtiles

to pull out just the `Feature` lines, remove the commas, filter for just the attribute you want, and then pipe the result to Tippecanoe.

To really do it right for arbitrarily-formatted JSON, you need a streaming JSON parser like Oboe (`npm install oboe`). Then you can make a `json2ndjson` script:

```
#!/usr/local/bin/node

var oboe = require('oboe');

oboe(process.stdin).on('node', '*', function(node) {
        if (node != null && node.type === "Feature") {
                console.log(JSON.stringify(node));
                return oboe.drop;
        }
}).done(function() {
}).fail(function(err) {
        console.err(err);
});
```

and then do

    cat tl_2015_06001_roads.json | ./json2ndjson | ndjson-filter 'd.properties.MTFCC === "S1400"' | tippecanoe -f -o s1400b.mbtiles

or even just do the filtering directly in the oboe loop instead of in a separate `ndjson-filter` stage of the pipeline.

It is kind of slow, though. Maybe it really should be directly in Tippecanoe, or at least I could pull out Tippecanoe's streaming JSON parser into something that could produce a stream of newline-delimited JSON objects quickly for use with line-oriented tools.

**Comment by ericfischer** [comment]
Great, glad it worked for you. I'll try to think of a good way to incorporate filtering cleanly into Tippecanoe.

**Comment by ericfischer** [comment]
Too late for today, but I added a `geojson2nd` command to [json-pull](https://github.com/ericfischer/json-pull) for future fast, convenient extraction of GeoJSON features to newline-delimited JSON.

Closing this since I already have another ticket about filtering directly within Tippecanoe.

**Comment by ericfischer** [comment]
Fixed in https://github.com/mapbox/tippecanoe/pull/462
