### ISSUE TITLE
Jitter is being added when simplifying points

### ISSUE THREAD

**Issue by waissbluth** [mapbox/tippecanoe#454]
When simplifying a point layer it seems that, at low zoom levels when density is being reduced, jitter is being added to the points. This is only noticeably when zooming in quickly. 

Is this the case, or is it that the coordinate precision used at low zoom levels results in what appears to be jitter (or, i guess, quantization) when zooming in and before the actual, high resolution layer kicks in?

Is there any way to avoid this? So that points don't move when zooming in, but rather, only new points appear and the already-loaded ones stay in place.

**Comment by ericfischer** [comment]
Locations at each zoom level are quantized to the resolution of that zoom, but there is no intentional jitter.

In theory it is possible to set a higher resolution at lower zooms but in practice this doesn't work because of limitations in the coordinate system that Mapbox GL uses internally.

It might be possible to stabilize the point locations between zooms by always keeping each point at the location it is quantized to in the lowest zoom that it appears in, but this might leave it a considerable distance from its correct location in high zoom levels.
