### ISSUE TITLE
Metadata Options + Parsing Error

### ISSUE THREAD

**Issue by jenningsanderson** [mapbox/tippecanoe#459]
When building tiles with version `1.21.0`, the output .mbtiles file is unreadable because of a parsing error in the json metadata; this does not happen when tiling with version `1.19.1` instead.

On that note, for building tilesets such as `osm-qa-tiles`, is the metadata table / and metadata per tile necessary to generate? Would there be performance gains during generation if this metadata were skipped? Would that violate the tile spec?

**Comment by ericfischer** [comment]
There was a bug in `1.21.0` generating the GeoJSON when there were long string attributes, and it should be fixed in `1.22.1`. Please upgrade, and let me know if you still see any problems.

You can use the `tile-join` in `1.22.1` to copy the tileset and regenerate the metadata table if necessary, or use `--no-tile-stats` to remove the tilestats portion of the metadata.

I doubt anyone is using the metadata table in `osm-qa-tiles` but I don't know. There is some argument in the `mbtiles-spec` repo (https://github.com/mapbox/mbtiles-spec/pull/47) about whether the `json` row ought to be part of the spec. (I say yes, since the unpacker requires it, but it could just as well be part of the vector tile spec instead of in the mbtiles spec.) The tilestats part of it *is* optional, but its absence makes unpacking much slower, because without it, the unpacker has to iterate through every tile to regenerate it.

There is some time cost incurred by the tilestats generation, but I think it is fairly minimal. In a small test I just tried, it took 98.5% as long without the tilestats as with them. (The only difference will be seen during the GeoJSON parsing phase, not during tiling.)

I'm not sure what per-tile metadata you're referring to. Can you clarify?

**Comment by jenningsanderson** [comment]
👍  Perfect, thanks for the info, this is incredibly helpful, I will update and re-run with `no-tile-stats`. The current version of `tippecanoe` in mason is `1.21.0`. 

The per-tile metadata I'm referring to is what comes through when passing tiles as `raw = true` in tile reduce; there are arrays of `keys` and `values` that sit alongside the `_features` object; perhaps I am wrong in how this works? ... I'm now imagining that _these_ are the values and that features reference these arrays....

**Comment by ericfischer** [comment]
Thanks! I'll update mason with the new version.

I hadn't realized that tile-reduce had a way to access the raw tile content instead of converting it to GeoJSON. But yes, the way the vector tile format works is that there are per-layer pools of attribute keys and values, and the features themselves refer to those keys and values by their integer indices, so I think those are the `keys` and `values` arrays that you are seeing.

**Comment by ericfischer** [comment]
The new version in mason will be https://github.com/mapbox/mason/pull/468

**Comment by jenningsanderson** [comment]
Thanks @ericfischer, this all makes sense and fixes my workflow.
