### ISSUE TITLE
conversion creates rogue characters, data missing.

### ISSUE THREAD

**Issue by dehyde** [mapbox/tippecanoe#474]
using Tippecanoe to translate geoJSON data to MBtiles resulted in missing data

some more information:
1. First attempt created a problematic file with many excessive "," characters, probably due to quotation marks in the original data.
2. After removing the quotation marks from the geojson, the result still had some extra "," characters, but much less. 
3. The resulting file has a lot of data missing.

<img width="892" alt="screen shot 2017-10-10 at 16 52 38" src="https://user-images.githubusercontent.com/32676977/31458786-c8ff9be4-aec9-11e7-8509-9b8474221ce0.png">

in this link are the geojson (without quotation marks), and the last version of the MBtiles (clean, data missing).

https://drive.google.com/drive/u/0/folders/0B454RJ8qKV38NVZ0ZnNDbTd2NVk

**actua result:**
<img width="765" alt="actual_result" src="https://user-images.githubusercontent.com/32676977/31458272-43d1e6bc-aec8-11e7-9687-e8bce5b77ac7.png">

**expected result**
<img width="780" alt="expected_result" src="https://user-images.githubusercontent.com/32676977/31458247-33dedc60-aec8-11e7-8631-4e69a1d38ab2.png">

**Comment by ericfischer** [comment]
I think the missing data you are seeing is because of Tippecanoe's default behavior of dropping a fraction of points at lower zoom levels to avoid excessively dense tiles. You can choose a lower base zoom with `-B`, but you can't go too low because your features have a lot of attributes, which will still make the tiles too big if you use a `-B` of less than 7.

To keep as many points as possible, use

    tippecanoe -r1 --drop-densest-as-needed -f -o out.mbtiles ged171_direct_from_site_quotemarks_removed_10-10_15-40.geojson

The `-r1` will make it try to keep them all, and the `--drop-densest-as-needed` will thin them out where it is unavoidable at zooms 0 through 6.

![screen shot 2017-10-11 at 1 06 46 pm](https://user-images.githubusercontent.com/1951835/31464060-157da69a-ae85-11e7-942f-f2966947c67d.png)

If you want to keep more points, you will need to reduce the attributes associated with each of them.

**Comment by dehyde** [comment]
tried the code you suggested
it's causing the unexpected "," again
by the way, the computer nearly overheated during the coversion process. don't know if it's supposed to be like that.

<img width="1047" alt="screen shot 2017-10-12 at 02 31 32" src="https://user-images.githubusercontent.com/32676977/31472149-9e080f9e-aef5-11e7-8a3a-4c12d0f50a92.png">

**Comment by ericfischer** [comment]
I have no idea what program you are seeing these errors in. Tippecanoe's output is vector tiles, not GeoJSON, so I don't think these errors are due to Tippecanoe.

The GeoJSON file you sent me has lots of character encoding errors (looks like UTF-8 text that has been sent through ISO-8859-1 to UTF-8 conversion again) but Tippecanoe is able to parse it.

**Comment by dehyde** [comment]
there's a json in the mbtiles metadata, this is what's been causing the 'unexpected "," ' (attaching screenshot). 

Anyway after cleaning that, the conversion worked very well with 
`tippecanoe -r1 --drop-densest-as-needed -f -o out.mbtiles ged171_direct_from_site_quotemarks_removed_10-10_15-40.geojson`

about reducing attributes - is it a result of the number of attributes or the number of characters in the attributes? will reducing some attributes have a bigger effect than reducing others?

thank you kindly for all your help

<img width="1146" alt="screen shot 2017-10-12 at 10 29 34" src="https://user-images.githubusercontent.com/32676977/31484262-4cc2fe4e-af38-11e7-9955-abb3fcbeddc4.png">

**Comment by nbulaj** [comment]
Hi @ericfischer . I have the same issue with some private GeoJSON data that consist of only Point features. I'm trying to convert it with `tippecanoe data.geojson  -o data.mbtiles -f -r1 --drop-densest-as-needed`, but unfortunately I lost at least 5 points (it is exists in the GeoJSON, but doesn't rendered on the map). Can you please say what options I need to play to create a proper full data vector file ?

**Comment by ericfischer** [comment]
Oh sorry, there was a bug in Tippecanoe's tilestats generation beginning in version 1.21.0, where when long attributes were elided from the tilestats, it would still generate the comma that would have separated the attribute.

Please upgrade to version 1.22.1 or newer and it should be fixed.

**Comment by ericfischer** [comment]
The length of the attributes will contribute more to making the tiles large than the number of attributes. If several features have exactly the same content for an attribute, it will only be stored once, so it helps if they are duplicated. Numbers will take up less space than strings; integers will take up less space than floating point numbers.

**Comment by nibygro** [comment]
@ericfischer the same problem. I have geojson with more than 350 000 Point features. I'm trying to convert it using tippecanoe (like this - `tippecanoe  -o data.mbtiles points.geojson`), but I'v got

> *** NOTE TILES ONLY COMPLETE THROUGH ZOOM -1 ***

So, I tried to convert the file like this: `tippecanoe  -o data.mbtiles points.geojson -r1 --drop-densest-as-needed` and all finished without errors.

But when I try to show generated MBtiles on the Mapbox GL JS then I didn't see some very important points on the map on my base zoom (12). They only can be seen only if I will hugely increase the zoom. So what am I doing wrong?

**Comment by ericfischer** [comment]
@nibygro You probably have a lot of attributes for each feature, and attributes take up a lot of space in the tiles. Try using `-y` to keep only the ones you really need, or reduce the length or precision of attributes so they can be stored more compactly.

**Comment by nibygro** [comment]
@ericfischer I tried to, but no matter if I store only "id" attribute with Numeric value - it drops my feature points anyway :(

**Comment by ericfischer** [comment]
If you share your data, I can take a look and see if I can see any obvious ways to make it work better. Unique IDs for features will always take up a lot of space, though, because none of the attribute data can even be shared between features.

**Comment by nbulaj** [comment]
I can't share this data because of NDA, but I can generate the same data, but with random (or not valuable) attributes. There it is - [data.geojson.zip](https://github.com/mapbox/tippecanoe/files/1431099/data.geojson.zip). Note that URLs is unique for all the features and I need to store them (for the popup, fox example).

**Comment by ericfischer** [comment]
Sorry, but 95 characters of unique text with each feature inherently takes up a lot of space in the tiles. You must choose between having a lot of features in each tile and associating a lot of data with each feature. The best I can suggest for this data is

```
tippecanoe -zg --drop-densest-as-needed --extend-zooms-if-still-dropping -f -o data.mbtiles data.geojson
```

which is complete at z16, and keeps as many features as it can at the lower zooms.
