### ISSUE TITLE
tippecanoe drops features when converting many GeoJSON files on different layers for one tileset

### ISSUE THREAD

**Issue by nbulaj** [mapbox/tippecanoe#475]
Hi. We try to generate one MBTiles file from the different GeoJSON files of the same format (_FeatureCollection_ of _LineStrings_), but different properties values with the following command:

`tippecanoe -o data.mbtiles -zg --no-line-simplification --drop-smallest-as-needed -f --named-layer='layer1':/path/layer1.geojson --named-layer='layer2':/path/layer2.geojson --named-layer='layer3':/path/layer3.geojson --named-layer='layer4':/path/layer4.geojson`

tippecanoe successfully converts all the data (without any errors or warnings), but the output file is too small (in comparison with a single converted GeoJSON file from the list below). Moreover, after uploading output vector data to Mapbox and trying to render it on the map we get only a few features on every layer. As the result we have a big amount of missed data (you can see this on attached the screen).

![Actual and Expected](https://user-images.githubusercontent.com/1443426/31550325-b2a0495e-b039-11e7-8af3-81ba3e1d6701.png)

So the question is: does _tippecanoe_ drops some data (maybe it is some kind of optimization) during the conversion of big amount of sources to different layers (not a one)? Or it is an error in tippecanoe options that we use? Thanx!

**Comment by ericfischer** [comment]
You said `--drop-smallest-as-needed`, so it is dropping whatever fraction of features it must to get the tile sizes down to 500K. The data for four layers is going to be bigger for the data for one layer, so that is why it drops more when you are trying to tile all four layers at once.

I am surprised that it does not give any warnings, though. It should be giving messages describing what fraction of features it is thinks it can keep.

**Comment by ericfischer** [comment]
Unless you really need unsimplified geometry, I would suggest not using `--no-line-simplification`. Turning off simplification like this will generally make your tiles bigger without much visual benefit.

**Comment by nbulaj** [comment]
@ericfischer in this case tippecano stops at some zoom level and output file has the size for about 400 kb. And, as you already understood, the data is missed too. I will attach the tippecanoe conversion log on Monday

**Comment by nbulaj** [comment]
@ericfischer without options like `--drop-smallest-as-needed` or `--drop-fraction-as-needed` I have the following output (just `-o data.mbtiles -zg -f  %all_the_json_files_and_layers%`):

> 4014833 features, 149967220 bytes of geometry, 51395705 bytes of separate metadata, 722136 bytes of string pool
> Choosing a maxzoom of -z10 for features about 258 feet apart
> Choosing a maxzoom of -z11 for resolution of about 209 feet within features
> tile 0/0/0 size is 636685 with detail 12, >500000    
> tile 1/0/0 has 200393 features, >200000    
> Try using --drop-fraction-as-needed or --drop-densest-as-needed.
> *** NOTE TILES ONLY COMPLETE THROUGH ZOOM 0 ***

What am I doing wrong?

**Comment by nbulaj** [comment]
Data we used (GeoJSON): [data.geojson.zip](https://github.com/mapbox/tippecanoe/files/1386810/data.geojson.zip) (100 000 features, but we have 20 files with data like this and trying to combine then by layers in one tileset file as I described above). You can just copy it 20 times and try to run tippecanoe to get one big tileset.

**Comment by ericfischer** [comment]
With the data you provided, duplicated 20 times, you can get as far as z6 by using `--no-feature-limit` to eliminate the restriction to 200,000 features per tile, but the data is ultimately still too big to fit at z7.

Fundamentally, there is a limit (500K) to the size of each tile, and the ways you can make large data fit is either:

* have fewer features
* have coarser geometry for the features
* have fewer or more compact attributes for each feature

In your case it looks like you have many repeated geometries so that you can have different attributes at different hours. I would suggest using a single feature for each block, and giving all the hours as attributes to the same feature, like `users_2230: 13, events_2230: 2, users_2300: 7, events_2100: 2, …`. It still might be too big, but it should be smaller than repeating the geometry.

**Comment by nbulaj** [comment]
@ericfischer one more question: if there are an ability to sort features by some criteria (by additional property value) in order to save the most important points? I have 10 features that I want to save on ever zoo, level and > 150 000 features of anther type than I can delete in order to reduce the density.

**Comment by ericfischer** [comment]
The best way to do this currently is to make one tileset of your special points with `-r1` to keep them all and another tileset of the regular points, and then use `tile-join` to merge the two together. There was another request like yours in https://github.com/mapbox/tippecanoe/issues/445 but I haven't figured out a good way to implement priority feature dropping.

**Comment by nbulaj** [comment]
Thanks @ericfischer, I used solution from the #445 with `"tippecanoe": { "minzoom": 12 }` for my data and _it solved the problem_ (but sometimes it drops the points anyway from the higher zoom O_o so it is visible for base zoom, but not on some higher one - with `-zg --drop-densest-as-needed -r1 --exclude=attr).`

**Comment by ericfischer** [comment]
Oh, thanks, I'll take a look at what's going wrong with the `minzoom`.
