### ISSUE TITLE
Issue with --detect-shared-borders

### ISSUE THREAD

**Issue by pranavn20** [mapbox/tippecanoe#487]
`tippecanoe --detect-shared-borders -o test.mbtiles hex.geojson`
Using --detect-shared-borders on hexagons results in oversimplification of the polygons, overlapping blocks and gaps. Refer to attached image. 
![image](https://user-images.githubusercontent.com/22625559/32471753-c5ea6eda-c313-11e7-9d11-9389843daaf6.png)

**Comment by ericfischer** [comment]
I can't debug this without a copy of your `hex.geojson`, but it may be the same problem I am working on in https://github.com/mapbox/tippecanoe/issues/482

**Comment by pranavn20** [comment]
Here is the file I'm using

[hex.geojson.zip](https://github.com/mapbox/tippecanoe/files/1451010/hex.geojson.zip)

**Comment by ericfischer** [comment]
I don't think this is actually a problem with `--detect-shared-borders`, since I am seeing the same behavior with or without it (although it may aggravate the problem by limiting the possible simplification of the hexes). As you can see from the logs during the run:

```
tile 6/10/24 size is 737747 with detail 12, >500000
tile 7/20/49 size is 1615923 with detail 12, >500000
tile 7/20/49 size is 737703 with detail 11, >500000
tile 8/41/99 size is 576060 with detail 12, >500000
tile 8/41/98 size is 637037 with detail 12, >500000
tile 8/41/99 size is 638335 with detail 11, >500000
tile 8/41/98 size is 704384 with detail 11, >500000
tile 9/82/197 size is 564845 with detail 12, >500000
tile 9/82/197 size is 563140 with detail 11, >500000
tile 9/82/197 size is 619062 with detail 10, >500000
```

there are more features than can fit in the tiles at zooms 6 through 9, so Tippecanoe keeps lowering the resolution of the tiles more and more until the tiling can succeed.

My main suggestion is to change your feature IDs from a string to a number so they will take a little less space, but it doesn't help very much.

```
tippecanoe -f -o test.mbtiles --drop-densest-as-needed --extend-zooms-if-still-dropping -zg hex.geojson
```

will drop features to reduce the tile sizes instead of lowering the tile resolution, but it still has many visible artifacts. The only thing that will really help is if you use fewer, larger hexes at low zoom levels.
