### ISSUE TITLE
Points are missing when viewing by MapTiler

### ISSUE THREAD

**Issue by KingElimy** [mapbox/tippecanoe#512]
I'v tried to make mbtiles from point data formatted as geojson and then viewed the output in MapTiler,but ended with seeing nothing(data do exist when open by db tools).
I'm confused while the lines and polygons data it does well,If @ericfischer you can take some time to have a look at this? And, I'm interested in how you managed to drop the points to make it fit the limits of a tile such as feature number,tile size,etc.
Hoping your reply!

**Comment by ericfischer** [comment]
Tippecanoe drops points at low zooms to keep a consistent size and visual density of points across zooms. You can use `-B0` or `-r1` to turn off point dropping. `-Bg` will try to guess an appropriate base zoom at which to keep all the points.

**Comment by KingElimy** [comment]
Thanks your reply.
The options to control it i have known from the ReadMe document,but it is the implementation that truly attracts me since i can not figure out the point to do it well.
Thank you again!

**Comment by ericfischer** [comment]
The base zoom guessing (`-Bg`) implementation is here: https://github.com/mapbox/tippecanoe/blob/5687ee041fc20467a578b639bf95baf89847f3b4/main.cpp#L1853

It goes through the features in order and calculates how many of them are in each tile in each zoom level, and chooses the zoom level where the largest tile has no more than 50,000 features.

The maxzoom guessing (`-zg`) implementation is here: https://github.com/mapbox/tippecanoe/blob/5687ee041fc20467a578b639bf95baf89847f3b4/main.cpp#L1770

It similarly runs through the features in order, but instead of counting features in each tile, it calculates the average of the log of the distances between adjacent features, and then chooses a zoom level that is high enough for the detail to be able to distinguish locations that are 1/8 of that distance apart.

**Comment by KingElimy** [comment]
Thanks a lot! 
Recently,I'm processing relatively large data with this tool,but it seems to be not good enough because of that points are totally dropped and road line segments are missing at lower level.
![tim1](https://user-images.githubusercontent.com/34496415/34190289-e02e7988-e57a-11e7-82b8-72b8c4e16a55.png)
![tim2](https://user-images.githubusercontent.com/34496415/34190292-e4618d2e-e57a-11e7-8e2d-0ab8231e56e9.png)
I'll try to use the option of -y and -j and some others,if there is any suggestions?

**Comment by ericfischer** [comment]
Using `-y` (or `-x`, etc.) to leave out all the attributes you don't need will be the best strategy for reducing the tile size.

It looks like you are using `--drop-densest-as-needed` or `--drop-smallest-as-needed` to make the low zooms work. If you don't need the identity of the short road segments to be correct but you do want them to draw, you might want to try `--coalesce-smallest-as-needed` instead to merge them onto other nearby roads instead of dropping them.

**Comment by KingElimy** [comment]
Yeah,I do used -aN and -as(--drop-densest-as-need).In fact,the  command is "tippecanoe -f -o bj_11.mbtiles -z11 -Z11 -aN -as -pS -y CNAME -y LEVEL -y CLASID -y FORM -y FUNCCLASS -y NAME -y IMPORTANCE -y TYPE -y KIND -y LINECODE -y TRAIN -y STATUS $srcs",I'll try your suggestion of --coalesce-smallest-as-need.
