### ISSUE TITLE
Is --minimum-zoom working right?

### ISSUE THREAD

**Issue by stevage** [mapbox/tippecanoe#519]
I'm surprised when using --minimum-zoom to see Tippecanoe apparently spending a lot of time working on zooms lower than that:

```
tippecanoe --drop-rate=g50   --drop-densest-as-needed --extend-zooms-if-still-dropping --read-parallel --force --simplification=10 --minimum-zoom=15 --maximum-zoom=15 --output=mbtiles/addresses.mbtiles address_main.json
For layer 0, using name "address_main"
3655450 features, 133567690 bytes of geometry, 8 bytes of separate metadata, 123320229 bytes of string pool
Choosing a drop rate of -r3170.400000 to keep 20.000000 features in tile 14/14789/10053.
  55.2%  8/231/157
```

Is this because:

* This is normal, and I just don't understand why.
* The output is misleading.
* Tippecanoe is indeed doing work it doesn't need to do.

**Comment by ericfischer** [comment]
It still has to go through the lower zooms to cut the features apart into higher-zoom tiles. If all your features fit into one tile at some level above 0, it will start with that tile instead of at z0, and it will skip over as many zooms as it can given the constraints of how many CPUs you have and how many files your OS allows a program to have open at one time.

(That said, I should do the experiment and make sure I am right that it is faster to go through the low zooms and split features apart rather than starting at the minzoom and letting all the threads read through the entire set of features.)

**Comment by stevage** [comment]
Ah, thanks very much for the explanation. That does make sense.
