### ISSUE TITLE
Set min & max zoom level per layer

### ISSUE THREAD

**Issue by ThomasG77** [mapbox/tippecanoe#550]
As I'm working on administrative areas, I would like to set for each layer a particular range of level with `-z` and `Z`

`docker run -it --rm   -v $(pwd)/data:/data   tippecanoe:latest   tippecanoe --output=/data/myoveralladmin-levels.mbtiles -z10 -Z6 -L myupperlevel:/data/myupperlevel.geojson -z14 -Z10 -L mysubupperlevel:/data/mysubupperlevel.geojson`

When I read the medata in the mbtiles, I see that both layers have the same min and max zoom levels using the last `-z` `-Z` values e.g `-z14 -Z10`

Is it already possible or does I miss a point? If not, is there an alternative like creating per layer with and per particular zoom ranges mbtiles & merging them or creating mbtiles with all layers for all zoom and then drop some layers for some levels?

Thanks for any direction about this topic

**Comment by ericfischer** [comment]
The way to do it currently is to add a `"tippecanoe": { "minzoom": …, "maxzoom": … }"` object to the features that you only want to appear in certain zoom levels.

You might find it more convenient to use a separate `tippecanoe` run for each layer, each with its own `-z` and `-Z` options, and then use `tile-join` to merge the intermediate mbtiles files into one final file.

It would be useful to be able to have more per-layer options, but I need to think of a more general way of how they could be specified.

**Comment by ThomasG77** [comment]
I've done it using your advice. Last remaining thing I do not understand is the fact that `json` in `metadata` table ignores the fact for my upper level all GeoJSON features are using `"tippecanoe" : { "maxzoom" : 12, "minzoom" : 6, "layer" : "mysubupperlevel"}` It remains with something like below e.g

```
{"vector_layers": [ { "id": "mysubupperlevel", "description": "", "minzoom": 0, "maxzoom": 14, "fields": {"ID": "String", "CODE1": "String", "NAME1": "String", "NAME2": "String"} }...
```
whereas I would expect `"minzoom": 6, "maxzoom": 12`

**Comment by ThomasG77** [comment]
For the second method, eveything work as expected. Thanks a lot. I close

**Comment by ericfischer** [comment]
Hmm, you're right, I think it's just using the overall tileset zoom levels rather than tracking which zoom levels the layers actually had any features in. I'll see if I can fix that.

**Comment by skeenp** [comment]
Can the min and max zoom be specified when specifying layers via -L{layer-json}? It would also be great to be able to access other options in a similar fashion. Would take a few steps away from the second option which I currently use.

**Comment by ericfischer** [comment]
The minzoom and maxzoom can't currently be set with `-L`, but that would be a good addition, and I'll look into adding it.

**Comment by RockDr** [comment]
Sorry to resurrect an old post, however the post above appears to be along the same lines of what I would like to achieve. I am trying to create mbtiles of street data, with different minzoom levels for each (i.e highways should appear in all tiles, but local streets should only be in zoomed in tiles). My processing is as follows (gdal converts shp to geoson, tippecanoe converts geoson to mbtiles, tile-join joins the individual mbtiles for each road class into a single mbtiles). I have a separate shapefiles for each street class (highways down to local streets), hence the individual mbtiles for each class. I am specifying the min and max zoom levels for each of of the tippecanoe runs. My issue is that the tile-join results in tiles larger than 500k. The post above mentions adding "tippecanoe": { "minzoom": …, "maxzoom": … }" object to the features. How do I do this (I'm a beginner). Is my above method along the right lines? I'm happy to take suggestions for a better processing routine, particularly as things may have moved on since the posts above in 2018. Thanks.
