### ISSUE TITLE
Dropping features

### ISSUE THREAD

**Issue by drewleonard** [mapbox/tippecanoe#598]
I'm using Tippecanoe to generate mbtiles from a 1.2 gb GeoJSON dataset of polygons (U.S. zipcodes). When I use the command provided in this repo: `$ tippecanoe -o out.mbtiles -zg --drop-densest-as-needed in.geojson`, some of the actual polygons seem to not get output into the mbtiles file. I've spent a good amount of time tweaking parameters for the `tippecanoe` command, but can't figure out whether any polygon features are being dropped altogether, and if so, how to prevent that.

Prompt:
```
❯ tippecanoe -o ou9t.mbtiles -zg --drop-densest-as-needed zipcode.geojson
```

Output:
```
For layer 0, using name "zipcode"
zipcode.geojson:1561: Expected a comma or colon
In JSON object {"type":"FeatureCollection","features":[{"type":"Feature","id":0}]}
173 features, 1648338 bytes of geometry, 1205 bytes of separate metadata, 1805 bytes of string pool
Choosing a maxzoom of -z1 for features about 142335 feet (43384 meters) apart
Choosing a maxzoom of -z11 for resolution of about 189 feet (57 meters) within features
  99.9%  11/585/797
```

My GeoJSON file _should_ have ~30,000 features (one per zipcode).

Please let me know what other useful information I can provide to clarify this issue, and thank you very much for any help.

**Comment by ericfischer** [comment]
Your error message

```
zipcode.geojson:1561: Expected a comma or colon
```

shows that Tippecanoe is encountering an error parsing line 1561 of your input GeoJSON file. Anything after line 1561 in the file is being lost, which probably explains your lost features. Check your input file and there is probably something formatted wrong in it.

(The `--drop-densest-as-needed` option might normally also cause some of the polygons not to appear in the output, because there are too many to fit in the tiles, but your output log does not show that any features are being dropped.)

**Comment by drewleonard** [comment]
@ericfischer 

This is really helpful—thank you for the prompt response. I'm going to keep hacking at this and will get back to you once I figure more out. Thanks so much.

**Comment by drewleonard** [comment]
Yeah, that was the issue. Fixed. Thanks again!
