### ISSUE TITLE
Issue when line is directly along the 180 degree meridian

### ISSUE THREAD

**Issue by samfader** [mapbox/tippecanoe#603]
In trying to upload graticules, I'm running into an issue with how the 180 degree meridian line displays in Mapbox Studio/GL JS. Example here: https://jsfiddle.net/yq42k1gd/

To get to that point, I took the attached graticule file and ran it through Tippecanoe to generate MBTiles. I then created a tileset in Studio and added it as a new layer to a style. Then I referenced this style in GL JS.

If one simply adds the GeoJSON directly, the problem does not occur: https://bl.ocks.org/samfader/de93704a1c26b0847f4e97c7a759946a

Let me know if there's any other info I can provide!

**Comment by ericfischer** [comment]
This should be fixed in https://github.com/mapbox/tippecanoe/pull/616

I ended up deciding to duplicate on both sides of the antimeridian any feature that comes within the z0 tile buffer of it, not just those features that directly run along it. I'm not 100% sure it's the right thing to do (and it touches a lot of test outputs), but it is consistent with what happens at other tile boundaries. If you set a buffer of 0, it duplicates only the features that are on the antimeridian or cross it.

**Comment by mourner** [comment]
@ericfischer I think that's the right choice — here's how geojson-vt handles this: https://github.com/mapbox/geojson-vt/blob/master/src/wrap.js#L8-L16

Basically it clips out the center world (with buffer), then merges in clipped buffered world on the left shifted to +360, and the right world shifted to -360.

**Comment by ericfischer** [comment]
Thanks @mourner. I think this will have equivalent behavior.

**Comment by ericfischer** [comment]
Merged https://github.com/mapbox/tippecanoe/pull/616
