### ISSUE TITLE
Precision issue with RhodeIsland example

### ISSUE THREAD

**Issue by qberthetSiradel** [mapbox/tippecanoe#664]
Hello,

I am having a precision issue with the RhodeIsland datasource. When decoding max zoom tiles and visualizing it in QGis, I have a precision error compared to original geoJson. 

I used both example command and basic tippecanoe command without special argument. I have 12 and 14 max zoom respectively.

Is there a implicit simplification on features? even on max zoom tiles?

diff with z12:
![diff z12 original](https://user-images.githubusercontent.com/44844790/48146567-91549e80-e2b5-11e8-99c2-c5ec3b962358.PNG)

diff with z14:
![diff z14 original](https://user-images.githubusercontent.com/44844790/48146570-91549e80-e2b5-11e8-937e-157768671f07.PNG)

**Comment by ericfischer** [comment]
In Tippecanoe, "simplification" always means dropping points from a polygon boundary or from a line, so I would call this a "precision" problem instead of a "simplification" problem. The precision of zoom level 12 tiles with the default detail (`-d`) of 12 is `360 / (2^(12 + 12)) / .00000274` ≈ 8 feet, which is not really good enough for building footprints. I would suggest using a higher maxzoom for better precision.

If you think there is a simplification problem too, you can use `--simplify-only-low-zooms` to prevent it from doing any simplification at the max zoom level.

**Comment by qberthetSiradel** [comment]
yes, you are right it is a precision problem. I tried with a higher detail arguments and it works well. Thank you.
