### ISSUE TITLE
reorder and coalesce cause features to go missing

### ISSUE THREAD

**Issue by jliebrand** [mapbox/tippecanoe#667]
I have some input (bit too large to add here), which results in missing features when I use reorder and coalesce.

I'm attaching the mbtiles of one tile that shows the problem (10/525/336), both with and without the coalesce. These were created with:
```
-Z10 -z10 -D14 -d14 --reorder --coalesce --no-feature-limit --drop-densest-as-needed
```
(and obviously the other one without reorder and coalesce to show the difference).

Notice the water features go missing when you coalesce...

[coalesce.zip](https://github.com/mapbox/tippecanoe/files/2576535/coalesce.zip)

**Comment by jliebrand** [comment]
Note: I've assumed that the drop-densest-as-needed does not play a role here. Because (and correct me if I'm wrong), if anything, coalescing the features should result in a smaller tile. So if features aren't being dropped in the normal case, they shouldn't be dropped in the coalesce case either?

**Comment by ericfischer** [comment]
If it doesn't say that it's dropping features, it shouldn't drop features, so if things are vanishing without a message about it, that's a bug.

Can you be clearer about what's being lost? The #osmwat layer seems to be there in both cases, so I don't see what is being lost. Is there another water feature layer?

What version of Tippecanoe are you using? There was a bug in `--coalesce`, fixed in 1.27.8, that could cause some features with non-identical attributes that had passed through an input filter to be coalesced even though they shouldn't have been, although that doesn't sound like the problem here.

My main theory is that the coalesced polygons may be getting too complicated and exposing a bug either in geometry cleaning or in rendering, and I'll be happy to investigate further if you can clarify which features are the ones that are having problems.

**Comment by jliebrand** [comment]
Sorry, I think you might be right that this is a rendering issue. I've created two styles that show the difference:
https://api.mapbox.com/styles/v1/liebrand/cjogw7vcz085o2smp9bbdhm7q.html
https://api.mapbox.com/styles/v1/liebrand/cjogw6fjj2b902so9zv0gb8i6.html

Near Ijmuiden in the Netherlands, you'll notice the osmwat layer breaks up near the locks in the coalesce style, see the attached video:

[ijmuiden.mp4.zip](https://github.com/mapbox/tippecanoe/files/2579806/ijmuiden.mp4.zip)

As for the reporting of dropping features; I think have seen a number of cases where it did drop features, but it didn't mention it on the command line. I think it's when the 200k limit of features is reached maybe? eg even if the tile is within the 400k limit, it might not include all features (and not report it) if that limit is reached, could that be true?

**Comment by ericfischer** [comment]
Normally it will exit with an error if the 200K feature limit is reached without you using `--drop-*-as-needed`. (But features that are too small to be represented in the tile resolution will be dropped silently.)

I wonder if it would help to do another simplification pass after coalescing, at least for polygons. There may be some overly complicated geometries being left as they are (aside from the cleanup that happens during unioning) instead of having their complexity reduced.

**Comment by ericfischer** [comment]
Closing since this seems to be a rendering problem. Please reopen if necessary.
