### ISSUE TITLE
Overzooming not working when adding multiple mbtiles

### ISSUE THREAD

**Issue by azizul-bkash** [mapbox/tippecanoe#688]
I have created Vector tiles with Tippecanoe in mbtiles format. I am using tileserver-gl for serving the Vector tiles. Firstly I am creating 20 mbtiles separately as different layers needed different Tippecanoe options. After that I join tiles with tile-join feature. In tilestats of mbtiles json file I am getting different minzoom and maxzoom for each layer. The problem is the layer became invisible after the maxzoom level, the overzooming is not working though I have assign minzoom and maxzoom in style json file. It's working if I create vectortiles with a single script by providing multiple json layer as the zoom is the same for each layers. But few of my layers need much precision level data so that I have to create maxzoom z15 for each layer. As a result mbtiles becoming too high in size and taking a lot of time to create vector tiles.

Moreover when creating vector tiles with multiple json a lot of data lost in zoom scale 10-11. Again point layers also behaving weirdly. Such as, a single point feature is showing 5-6 times (See the attached image below).

What will be the best options for creating vector tiles with tippecanoe. Am I in the right track for establishing a self-hosted vector tiles server with Tippecanoe and Tileserver-GL?

![untitled](https://user-images.githubusercontent.com/41333705/50157919-dd572200-02fc-11e9-9c26-3a9957695b6d.png)

**Comment by ericfischer** [comment]
This is unfortunately a limitation of how tile compositing and rendering works, and can't be fixed in Tippecanoe itself. If any layers are defined for a tile, it will use only the layers that are explicitly part of that tile rather than going up to the parent tiles to overzoom data for layers that are not defined in the higher-zoom tile. (`tile-join` now gives a warning when joining tilesets that have different zoom ranges.)

If you use Mapbox tile serving and upload the mbtiles for each layer separately and then use server-side compositing of the layers, it will overzoom the data from tilesets that have a restricted zoom range when serving composite tiles at higher zooms. It may be possible to make your tile server do something similar but I don't know anything about Tileserver-GL and can't give advice about it.
