### ISSUE TITLE
Overzooming in tile-join

### ISSUE THREAD

**Issue by e-n-f** [mapbox/tippecanoe#693]
There has been some recent confusion in https://github.com/mapbox/tippecanoe/issues/692 and https://github.com/mapbox/tippecanoe/issues/688 about tile-join behavior when joining tilesets with different zoom ranges. It might be good to have an explicit `--overzoom` option to overzoom tiles from tilesets with a lower maxzoom when joining them to a tileset with a higher maxzoom.

**Comment by kdanaher** [comment]
I brought this up in another thread yesterday and was going to create a new issue, but saw this here.

Currently, joined tilesets using tile-join are not overzoom enabled _except_ for joined tilesets which share a common maximum-zoom. 

If I have a tileset that has no need for overzooming beyond a set max-zoom, this isn't a problem. But for other tilesets which I would like to render only to a certain zoom, but remain capable of overzooming, I have to either keep them as isolated source tilesets, or create each tileset to the highest max-zoom of the batch.

A way to add a flag which would preserve overzooming capabilities for each tileset added (despite their processed max-zoom) would be a great addition to tile-join

**Comment by leearmstrong** [comment]
I just stumbled upon this exact issue today.

I have a few tile sets with differing maximum zoom levels.  Some of them seem to disappear and won't overzoom.

Is there a way around this yet?

**Comment by kdanaher** [comment]
@leearmstrong I believe the only workaround at this time is to process each of your tilesets to a common max-zoom. Then, when you tile-join them, overzoom will be enabled across the separate layers/tilesets.

**Comment by Dylansc22** [comment]
Happy 2 year anniversary of the last comment on this issue! Haha, any possible progress on the horizon?

`tile-join` allowing for an `--overzoom` flag would really be helpful. Having `tile-join` require every tileset have the same `--maximum-zoom` is really limiting in how one must organize there data, and considering Mapbox only allows for a maximum of 15 tilesets in a Map-style, it would really allow me to add both data and detail! 

As discussed above, the best solution is what @kdanaher suggests. This will obviously you to "group" your data by zoom level... so at least for myself, when trying to be efficient with my final the number of tilesets for work. I group the tilesets with `tile-join` based on zoom levels such as `low-zoom.mbtiles` `intermediate_zoom.mbtiles` `high_zoom.mbtiles`, rather than grouping the data by the type of data (such as `parks.mbtiles`, conservation_area.mbtiles`). 

@ericfischer Shall I check back in 2 more years =P

**Comment by e-n-f** [comment]
This will be fixed in https://github.com/felt/tippecanoe/pull/131
