### ISSUE TITLE
Points appear twice in MapboxGL where there is only one point in geojson

### ISSUE THREAD

**Issue by PennyBeames** [mapbox/tippecanoe#699]
Quick question: I have a tileset with ~36000 points spread across the globe. When I zoom in, individual points appear in duplicate or triplicate for reasons I can't figure out. Zooming in and out a few times seems to sort things out, but rather than there being one point, from the way the point borders look it seems that the duplicate points are just sitting really close together. Is there a setting I'm missing that would prevent this from happening? Is it an issue with there being points very close to the edges of tiles?

I'm processing using -z12 -Z1 because the max zoom on my map is 12. I've set -b0 to remove the 5 pixel buffer. The issue appears between zoom levels 10 and 12. Insights?

Much thanks for your help.

**Comment by ericfischer** [comment]
The problem is on the GL side, and what is going on is that the features are being drawn both from the zoom level you are actually looking at as well as overzoomed from a parent tile. They are not at exactly the same location because the parent tile has lower location precision than the child tile. I *think* that what causes it is that if any features are being overzoomed from a tile, they all are, even if part of the area being overzoomed into is already covered by more detailed data.

I am not sure if it will fix it, but I should do the experiment of making sure that if Tippecanoe outputs a tile, it also outputs the other three quadrants of the same parent tile, even those tiles they are empty, and see if that helps.

**Comment by PennyBeames** [comment]
Man, you are lightning fast. Awesome, I'll give this a try.

**Comment by PennyBeames** [comment]
Ready for my very hack solution? (I should have tried this before, but I didn't think of it till you mentioned the overzooming issue.) I've processed the same geojson file using -z18 rather than -z12. Because my Mapbox maxZoom is set to 12, the user is prevented from zooming in close enough to replicate the problem that I imagine has now been shuffled to zoom levels 16 through 18. 

Not pretty, but it seems to work!

**Comment by ericfischer** [comment]
Great, I'm glad you were able to work around it!
