### ISSUE TITLE
How to make raw epsg:4326 coordinate tiles follow specified tile_id rule

### ISSUE THREAD

**Issue by KingElimy** [mapbox/tippecanoe#739]
I just want to make tiles keep raw wgs84 lonlat coordinate, but the tile_id should follows as
nX = 2^(level+1), nY = 2^(level), and the origin is top left.
what should i do except changing the project method which i mentioned in #546, wishes your tips,thanks :)

**Comment by ericfischer** [comment]
I'm not sure I entirely understand what you are trying to do, but if you want a different tiling scheme,

https://github.com/mapbox/tippecanoe/blob/945d80400b6c3bdbd73606a19351cb45c52e707d/mbtiles.cpp#L84

is probably the easiest place to inject it. Notice that the `y` coordinate is already transformed here because the Y axis is swapped in the TMS tiling scheme used in mbtiles compared to the XYZ scheme used in web map URLs and throughout the rest of Tippecanoe.

**Comment by KingElimy** [comment]
oh,what i what is the tile scheme follows the rule,equalize the world by latitude and longitude,at zoom level z,there will be nXTiles=2^(z+1) in columns and nYTiles=2^(z) in rows, and the zoom level starts from level 0. for example,zoom level 1,it will be 
![图片2](https://user-images.githubusercontent.com/34496415/54729128-b12d9480-4bbc-11e9-9292-f44b025f8d8f.jpg)
[reference section EPSG:4326](https://www.cnblogs.com/ytwy/p/6813948.html)
but,if i only inject the project method to calculate y as
 `long long lly = (n>>1) * ((-lat + 90) /180);`
the result of zoom level 1 will be only four tiles 
![图片3](https://user-images.githubusercontent.com/34496415/54729554-3d40bb80-4bbf-11e9-973c-8e87d3d783dd.jpg)
so,i want to know what i need to do next

**Comment by ericfischer** [comment]
There are always 2^z tiles in each direction in zoom level z. If you want, you can change `mbtiles_write_tile` to pretend that it is writing zoom level 1 when it is actually writing zoom level 2, so that there will be 4x4 tiles instead of 2x2, but there is no easy way to change the 2^z rule.
