### ISSUE TITLE
Tile size not decreased with using options for linear features

### ISSUE THREAD

**Issue by harry-wilson** [mapbox/tippecanoe#749]
I've used Tippecanoe to create .pbf vector tiles from a GeoJSON file including streets as LineString. The snippet below is the command to produce .pbf files in zoom level 7 via different options, but none of them decrease the volume size of tiles. 
`tippecanoe --no-tile-compression -z7 -Z7 -e road/ input/road.geojson`

Options used to decrease the tile size:
> --drop-densest-as-needed
> --drop-fraction-as-needed
> --drop-smallest-as-needed

Also using `--no-feature-limit --no-tile-size-limit` mode, tile sizes are the same as the case of using simplification options. I've applyed GeoServer to create vector tiles which provides lower tile size in comparisson with Tippecanoe. Why this options don't have any impact on tiles and how can I achive lower size for them?

**Comment by ericfischer** [comment]
If your streets are a complicated MultiLineString feature instead of many features, it may be that nothing can be dropped because these options only drop entire features, never individual components of a feature.

If your tiles are large, it may be because of the `--no-tile-compression`, if GeoServer normally compresses tiles.

Another possibility is that GeoServer uses a higher level of line simplification by default. You can use `-S` to increase the level of simplification.

GeoServer may also use a smaller buffer around the edges of tiles. You can use `-b0` to turn off the tile buffer if you don't need it.

**Comment by harry-wilson** [comment]
Thanks @ericfischer. No, the GeoJSON features are in the form of LineString which should be considered in the simplification process as you said. I think the `--no-tile-compression` command prevent to create MBtile files to produce raw 'PBF' as Geoserver does and also we need this. I want features to have some level of simplification to decrease the tile size especially in low zoom levels, but using different commands won't produce any changes in the result.

**Comment by ericfischer** [comment]
If you would like me to look into this, please provide samples of your input data and of the tiles that GeoServer produces from it. I can't do anything without a clearer idea of the expected results.

**Comment by harry-wilson** [comment]
This is the sample data I've used to create vector tiles. I would appreciate if you can take a look at it. 
[tippecanoe_geojson_test.zip](https://github.com/mapbox/tippecanoe/files/3145227/tippecanoe_geojson_test.zip)
And the following is the sample vector tile generated by GeoServer and Tippecanoe.
[pbfs.zip](https://github.com/mapbox/tippecanoe/files/3145231/pbfs.zip)
