### ISSUE TITLE
multiple, separate streams into tippecanoe?

### ISSUE THREAD

**Issue by aaronpdennis** [mapbox/tippecanoe#76]
Just like reading multiple files with tippecanoe to output vector tiles with multiple layers, is it possible to send multiple data streams into tippecanoe to create vector tiles with multiple layers?

Not sure if I'm thinking about this the right way. I want to run a process that is outputting GeoJSON objects and I want tippecanoe (or something else?) to separate the features into multiple layers in the vector tile output.

Below is what I'm currently doing with separate files, but I'd prefer to not have to write the files to disk, instead just send their data right into a single vector MBTiles (via tippecanoe?), ultimately for uploading through the Mapbox upload API.

```
tippecanoe \
  -z 14 -Z 13 \
  -d12 -D12 \
  -b 20 \
  -pc -f \
  -o hdm.mbtiles \
    hdm-data/hdm_label.json\
    hdm-data/water_source.json \
    hdm-data/communication.json \
    hdm-data/electric_utility.json \
    hdm-data/sanitation.json \
    hdm-data/emergency.json \
    hdm-data/medical.json \
    hdm-data/building_condition.json \
    hdm-data/road_condition.json \
    hdm-data/site.json
```

...  outputs an .mbtiles file with  ...

<img width="308" alt="screen shot 2015-08-08 at 3 09 51 pm" src="https://cloud.githubusercontent.com/assets/8019997/9151819/a581c690-3ddf-11e5-862f-b9cee842265b.png">

Maybe tippecanoe isn't the right tool for this?

**Comment by ericfischer** [comment]
In most modern shells you could do

    tippecanoe -o whatever.mbtiles <(command1) <(command2) ...

but that's not very useful because you can't control what the layers are named, and they will end up with weird names.

There's nothing conceptually too hard about making multiple layers from a single stream; the tricky part is just how to specify when they start and what they are named. Maybe there could be a magic JSON token that begins a new layer and specifies its name? Or each feature could specify the layer name that it wants to be part of as one of the properties. I'm not sure what really makes sense, so if you have ideas about what would seem natural and useful, please say!

**Comment by aaronpdennis** [comment]
I think each feature specifying a layer name as one of the properties would make a lot of sense, perhaps via an option to watch for a property "layer" that separates the features.

Thanks for the response, very helpful. I've looked around a bit more and I think the solution I need is a DynamoDB --> cardboard --> tilelive setup for serving constantly updating global vector tiles. I'll close this for now because I think that's the solution I need.
