### ISSUE TITLE
multiple country labels when transform in mbtiles

### ISSUE THREAD

**Issue by nyxx22** [mapbox/tippecanoe#784]
![Selection_020](https://user-images.githubusercontent.com/52417249/63172820-38d1df00-c047-11e9-950f-3bb24f6cf7c2.png)

someone know reason of this issue and how to fix it????

**Comment by ericfischer** [comment]
I think what you are seeing here is that every outer ring of a MultiPolygon feature is being labeled separately, so islands get their own label. You should probably generate a separate Point layer that is used just for labels so that there is only one label per feature. You can use https://github.com/mapbox/polylabel to calculate optimal label points.
