### ISSUE TITLE
Question: When serializing to tile...

### ISSUE THREAD

**Issue by CraigglesO** [mapbox/tippecanoe#786]
When serializing to a tile, why do Vector Tiles convert data to the extent 0-4096 (technically -2048 - 2048?

I've been looking everywhere on why the WebGL engine prefers this projection. Isn't it a little lossy this way at low zooms?

What are the advantages?

What does the new projection represent?

I looked a little at tippecanoe source code and mapbox-gl-js source.. but I'm still a little bit lost.

edit - i forgot to add that my theory is that it is projecting data to an enlarged 512x512 "image"... and since the bounds, and zoom are known, you are just reconstructing the tile coords after? But in the case of mapbox-gl, it seems to rebind the values to 0 - 1 which must just be how the uMatrix works in that case.

**Comment by springmeyer** [comment]
Have a look at https://docs.mapbox.com/vector-tiles/specification to learn more.

> I've been looking everywhere on why the WebGL engine prefers this projection. Isn't it a little lossy this way at low zooms?

Yes, it is lossy by design. Vector tiles are intended to be efficient for renderers are are not intended to be a high fidelity data storage format.

> What are the advantages?

Conversion to integer coords in the `extent` allows for much smaller tiles (and better compression ratios) than storing original floating point values.

> What does the new projection represent?

See `vector tile grid coordinates` at https://docs.mapbox.com/vector-tiles/specification/#encoding-geometry. In short it is a local (to a tile) coordinate system. The, given an assumed geographic projection and a tile z/x/y you can decode it in the right screen space for a map client (without incurring the memory penalty of going back to floating point coordinates in geographc space).

> I looked a little at tippecanoe source code and mapbox-gl-js source.. but I'm still a little bit lost.

Tippecanoe is just one implementation that depends on the Mapbox Vector Tile spec (and a complex one!). See the spec to learn, or look at simple parsers on top of it like https://github.com/mapbox/vector-tile-js.

**Comment by ericfischer** [comment]
4096 is sufficient because:

* A tile as rendered by Mapbox GL is nominally 512 pixels on the screen
* On a high resolution screen, this is 1024 physical pixels
* When overzoomed nearly to the next zoom level, it occupies 2048 physical pixels
* An extent of 4096 still allows some subpixel positioning, even with this scaling.

**Comment by CraigglesO** [comment]
Thanks guys 👍
