### ISSUE TITLE
Caching in tippecanoe

### ISSUE THREAD

**Issue by srinivasrk** [mapbox/tippecanoe#795]
First off thank you for this amazing tool ! 🎉 
Is there anyway we can cache the tippecanoe? We have a service that generates map tiles every one hour. Is there anyway we can cache it to improve performace.
I'm already using multiple processors to improve the speed.

**Comment by ericfischer** [comment]
Sorry, there are no current plans to add an incremental update feature to Tippecanoe. The best you can do currently is to do a separate run of Tippecanoe for the new features and then to use `tile-join` to merge it with an existing tileset of previously existing features.

**Comment by srinivasrk** [comment]
Thank you @ericfischer ! When I do a tile join of say 50 tiles (each of 80mb) I end up with `Killed/390`. My server is 16gigs of ram with 8CPU any thoughts? Also tile join takes a couple of minutes to bootstrap (no cpu usage for couple of minutes) after which all CPU starts getting hogged before it is killed.

**Comment by ericfischer** [comment]
You might want to check the output of `ulimit -a` and see if there are any unreasonably low limits set there.

I am surprised tile-join is so slow to start up and that it uses very much memory at all, since it normally should only have the data for one tile at a time per CPU in memory. If you can put copies of your files online somewhere, I can take a look and see if I can reproduce the problem.
