### ISSUE TITLE
technical details about "detail"

### ISSUE THREAD

**Issue by anandthakker** [mapbox/tippecanoe#92]
@ericfischer If it isn't horrendously complicated, do you think you could give a quick nutshell of the technical effects of the `detail` level?

The "Geometric Simplifications" part of the readme is helpful, but I'm just wondering which specific parts of the whole algorithm are controlled by `-d` and `-D`, since it seems like the simplification tolerance is a function of only the zoom level, and the point dropping rate is a different parameter.

Thanks!

**Comment by ericfischer** [comment]
Oh, sure @anandthakker, sorry to be confusing. The `-d`/`-D` detail (and the automatic detail reduction when tiles are too big) affects the following things:

  * The resolution of the coordinates within the tile itself. A detail of 7 (128 units per tile) is below the resolution of the screen, so things will look coarse. Detail of 8 (256 units per tile) or 9 (512 per tile) is the screen resolution for regular and retina screens, respectively, so should be sufficient for most drawing, but may still cause things to look visibly gridded. Detail beyond 9 allows overzoomed tiles to still draw at full screen resolution, and allows the texture to be more visible when there are overlapping features. The reason to use a lower detail is that each reduction in detail saves 2 bits of space from each set of feature coordinates.

  * The dropping of invisible features. Any line or polygon whose bounding box is entirely within a single pixel (in tile coordinates, not screen coordinates) would never cause anything to be drawn, so it is dropped from the output tile. If there are many small objects (say, individual blocks or streets at a low zoom level), a lower detail will mean that there are more of them that would never draw anything and can safely be left out, saving space.

  * Line and polygon simplification. These are simplified with respect to the tile coordinate system, not with respect to the zoom level, so lower detail means more points that have no impact on drawing and get simplified away. (Simplification could be zoom-level-specific instead, but that's now how I did it, since the appropriate thing seemed to be to leave out drawing instructions that would have no visible impact at whatever detail was being used for the tile coordinates.)

The point-dropping rate is independent of detail. The points that it drops are chosen by zoom level, not detail. Gamma-reduction feature drawing with `-g` is also relative to the zoom level, not the tile detail.

I hope that clears things up a little!

**Comment by anandthakker** [comment]
Ahhhh, okay cool!  Makes lots of sense, thanks @ericfischer.  And thanks for the whole thing--it's so nice to use.
