### ISSUE TITLE
Lost samll area

### ISSUE THREAD

**Issue by guyanf** [mapbox/tippecanoe#966]
Hi guys:
I have a polygon Geojson file, when I create tiles, some small areas were lost.
Geojson file : [geojson download](https://github.com/guyanf/issues_pic/blob/main/github/lmwz_17_20.geojson)

command: 
tippecanoe -Z 17 -z 20 -pC -pf -pk -pt -ab -Q --no-tiny-polygon-reduction -pS --buffer=30 --layer=lmwz --force -o ./data/lmwz_17_20.mbtiles ./data/lmwz_17_20.geojson

picture of Geojson: 
![json_lost_small_area](https://user-images.githubusercontent.com/9711184/218672558-1c3aecea-70fe-4a35-9116-382db96f8458.png)

picture of tiles: 

![tile_lost_small_area](https://user-images.githubusercontent.com/9711184/218672654-522a61ba-c788-4f0b-8877-73b7ae29d906.png)

How can I fix my command?

Thanks a lot.
Thomas

**Comment by e-n-f** [comment]
I think this was a bug in Tippecanoe's polygon area calculations, which could in some circumstances overflow and choose the wrong winding order for a polygon. It has been fixed in the Felt version of Tippecanoe, https://github.com/felt/tippecanoe.

Mapbox:
<img width="1167" alt="Screen Shot 2023-02-14 at 10 59 05 PM" src="https://user-images.githubusercontent.com/1951835/218955402-cc0c2d6b-4c1d-41d7-a5c4-36a51b09fd17.png">

Felt:
<img width="1167" alt="Screen Shot 2023-02-14 at 10 59 29 PM" src="https://user-images.githubusercontent.com/1951835/218955509-783006ce-61dc-43ce-a8ce-b15716ce5e47.png">

**Comment by guyanf** [comment]
@e-n-f Hi, thank you. 
All is OK.

Thomas
